LPS-192162
liferay-bpm-qa/liferay-portal pull request #1002
Opened 2023-08-04 17:47 UTC by sirfabios

2023-08-04 17:47 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-08-04 17:49 UTC, sirfabios commented
ci:test:sf

2023-08-04 17:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/7019/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7019/jenkins-report.html">here</a>.</b></p>

2023-08-04 17:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/43a8fc59fac7ddba761602493e22d04eec7b94d4">43a8fc59fac7ddba761602493e22d04eec7b94d4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/sirfabios/liferay-portal/tree/LPS-192162">LPS-192162</a><br/>Branch GIT ID: <a href="https://github.com/sirfabios/liferay-portal/commit/af55acb5409f6cd80510e271b6c40a63d61d7349">af55acb5409f6cd80510e271b6c40a63d61d7349</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7019/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7019/jenkins-report.html">here</a>.</h5></details></html>

2023-08-04 17:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7019/">test-portal-source-format#7019</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7019/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1002">liferay-bpm-qa#1002</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2400219382">[master] ci:test:sf - sirfabios &gt; liferay-bpm-qa - PR#1002 - 2023-08-04[10:49:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/25810/">publish-testray-report#25810</a><br/></div></div>

2023-08-08 06:32 UTC, timpak commented
@sirfabios there isn't a generic path for this? I'm almost certain there should be since this feature is highly likely to be used by other component teams, like Echo.

2023-08-09 13:15 UTC, sirfabios commented
Hi @timpak 
I hadn't found com, so I made this path.
I will search again after I finish the activities I'm doing.

2023-08-10 14:39 UTC, sirfabios commented
Hi @timpak 
I googled, found this NavBar#NAV_ITEM_REDIRECTION, he sees that the object name is there, but doesn't click.

2023-08-10 16:13 UTC, sirfabios commented
I resent a generic path.

2023-08-10 16:14 UTC, sirfabios commented
ci:test:sf

2023-08-10 16:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/4864/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4864/jenkins-report.html">here</a>.</b></p>

2023-08-10 16:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9b9c8fb8ca1d46ef6dab8c306728ac782a8c962f">9b9c8fb8ca1d46ef6dab8c306728ac782a8c962f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/sirfabios/liferay-portal/tree/LPS-192162">LPS-192162</a><br/>Branch GIT ID: <a href="https://github.com/sirfabios/liferay-portal/commit/74fe86f8969475594835129dc095cf4ad837ab58">74fe86f8969475594835129dc095cf4ad837ab58</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/4864/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4864/jenkins-report.html">here</a>.</h5></details></html>

2023-08-10 16:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/4864/">test-portal-source-format#4864</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4864/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1002">liferay-bpm-qa#1002</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2404172147">[master] ci:test:sf - sirfabios &gt; liferay-bpm-qa - PR#1002 - 2023-08-10[09:15:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/17701/">publish-testray-report#17701</a><br/></div></div>

2023-08-10 17:12 UTC, timpak requested changes
@sirfabios please see my suggestion below.

2023-08-10 17:12 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/paths/VisualizeObjectDisplayPage.path
> +		<td>//div[contains(@class,'collapse menubar-collapse')]//a[contains(.,'${key_pluralLabelName}')]</td>
Do we need to include `collapse` the path? Can we just use:
`//div[contains(@class,'menubar-collapse')]//a[contains(.,'${key_pluralLabelName}')]`

2023-08-11 14:52 UTC, sirfabios commented
ci:test:sf

2023-08-11 16:55 UTC, timpak commented
ci:forward

2023-08-11 16:55 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-08-11 18:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/6457/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6457/jenkins-report.html">here</a>.</b></p>

2023-08-11 18:54 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b77fc36c542d4d18f5bf3d8ed023029ca4a4722e">b77fc36c542d4d18f5bf3d8ed023029ca4a4722e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/sirfabios/liferay-portal/tree/LPS-192162">LPS-192162</a><br/>Branch GIT ID: <a href="https://github.com/sirfabios/liferay-portal/commit/50ad6580c5a8a4ef466cfaf5dd2c8cba99b6d65e">50ad6580c5a8a4ef466cfaf5dd2c8cba99b6d65e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6457/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6457/jenkins-report.html">here</a>.</h5></details></html>

2023-08-14 14:37 UTC, timpak commented
ci:forward

2023-08-14 14:37 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-08-14 14:37 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2023-08-14 16:41 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-16.liferay.com/job/forward-pullrequest/442//consoleFull)

2023-08-14 16:43 UTC, closed without merging

2023-08-14 16:43 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/139172
[Console](https://test-1-16.liferay.com/job/forward-pullrequest/442//consoleFull)