LPS-161962
liferay-bpm-qa/liferay-portal pull request #104
Opened 2022-11-01 13:26 UTC by Natanaelbenvindo

2022-11-01 13:30 UTC, Natanaelbenvindo commented
ci:test:sf

2022-11-01 14:38 UTC, rafaellajordao commented
ci:test:sf

2022-11-01 14:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/4550/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4550/jenkins-report.html">here</a>.</b></p>

2022-11-01 14:41 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2e1381f9732e18b04de4b7dc3a469e54e197217d">2e1381f9732e18b04de4b7dc3a469e54e197217d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Natanaelbenvindo/liferay-portal/tree/LPS-161962">LPS-161962</a><br/>Branch GIT ID: <a href="https://github.com/Natanaelbenvindo/liferay-portal/commit/20be74a5015115713a470b9adf67834f9e43df0f">20be74a5015115713a470b9adf67834f9e43df0f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/4550/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4550/jenkins-report.html">here</a>.</h5></details></html>

2022-11-01 15:07 UTC, rafaellajordao requested changes

2022-11-01 15:07 UTC, rafaellajordao commented on portal-web/test/functional/com/liferay/portalweb/macros/Form.macro
> +			locator1 = "Checkbox#ANY_CHECKBOX");
oi Natanel!

Sobre essa macro, como ela se tratar de setar uma configuracao especifica, acredito que o nome deveria ser diferente. Por exemplo: **configureOneSubmissionPerUser**. Deixando assim mais facil de entender o que essa macro faz! :)

Sobre a variavel _checkboxName_, e ineteressante que ela aponte para a checkbox que ela esta clicando, entao inves de apenas "Submissions" deve ser **"Limit to One Submission per User"**!

2022-11-01 15:07 UTC, rafaellajordao commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/FormsSubmissions.testcase
> +		Form.configureSubmissions();
Da uma olhada no comentario sobre essa macro! Precisa alterar o nome dela aqui tambem :)

2022-11-01 16:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/4550/">test-portal-source-format#4550</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4550/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/104">liferay-bpm-qa#104</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2027719351">[master] ci:test:sf - Natanaelbenvindo &gt; liferay-bpm-qa - PR#104 - 2022-11-01[07:38:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/16663/">publish-testray-report#16663</a><br/></div></div>

2022-11-01 17:46 UTC, rafaellajordao commented
ci:test:sf

2022-11-01 17:46 UTC, rafaellajordao approved these changes

2022-11-01 17:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2e1381f9732e18b04de4b7dc3a469e54e197217d">2e1381f9732e18b04de4b7dc3a469e54e197217d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Natanaelbenvindo/liferay-portal/tree/LPS-161962">LPS-161962</a><br/>Branch GIT ID: <a href="https://github.com/Natanaelbenvindo/liferay-portal/commit/5004ceafe055936884008799576403fe164512d3">5004ceafe055936884008799576403fe164512d3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/4568/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4568/jenkins-report.html">here</a>.</h5></details></html>

2022-11-01 21:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/4568/">test-portal-source-format#4568</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4568/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/104">liferay-bpm-qa#104</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2028031949">[master] ci:test:sf - Natanaelbenvindo &gt; liferay-bpm-qa - PR#104 - 2022-11-01[10:46:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/16730/">publish-testray-report#16730</a><br/></div></div>

2022-11-07 14:17 UTC, rafaellajordao commented
ci:forward

2022-11-07 14:19 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-11-07 14:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/3307/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3307/jenkins-report.html">here</a>.</b></p>

2022-11-07 14:24 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3c5f15fac195328784d279d043c9bab5f5f017d7">3c5f15fac195328784d279d043c9bab5f5f017d7</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Natanaelbenvindo/liferay-portal/tree/LPS-161962">LPS-161962</a><br/>Branch GIT ID: <a href="https://github.com/Natanaelbenvindo/liferay-portal/commit/f45afb7ba09a13c4b48fcdf83b008074a1177c83">f45afb7ba09a13c4b48fcdf83b008074a1177c83</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/3307/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3307/jenkins-report.html">here</a>.</h5><pre>Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
  at java.net.PlainSocketImpl.socketConnect(Native Method)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  at java.net.Socket.connect(Socket.java:589)
  at java.net.Socket.connect(Socket.java:538)
  at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
  at sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:211)
  at sun.net.www.http.HttpClient.New(HttpClient.java:308)
  at sun.net.www.http.HttpClient.New(HttpClient.java:326)
  at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
  at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
  at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.toInputStream(JenkinsResultsParserUtil.java:4325)
  at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.toBufferedReader(JenkinsResultsParserUtil.java:3956)
  at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.toString(JenkinsResultsParserUtil.java:4692)
  at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.getJenkinsBuildProperties(JenkinsResultsParserUtil.java:2129)
  ... 99 more
[beanshell] Created cache file in /tmp/jenkins-cached-files/-734893033.txt

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:15056: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-source-format.xml:122: Sourced file: inline evaluation of: ``                import com.liferay.jenkins.results.parser.AntUtil;         import com.lifer . . . '' : TargetError : at Line: 201 : in file: inline evaluation of: ``                import com.liferay.jenkins.results.parser.AntUtil;         import com.lifer . . . '' : throw e ; 

Target exception: java.lang.RuntimeException: java.net.ConnectException: Connection timed out (Connection timed out)</pre></details></html>

2022-11-07 14:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/3307/">test-portal-source-format#3307</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3307/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/104">liferay-bpm-qa#104</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2037888113">[master] ci:test:sf - Natanaelbenvindo &gt; liferay-bpm-qa - PR#104 - 2022-11-07[06:20:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/12279/">publish-testray-report#12279</a><br/></div></div>

2022-11-07 14:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/5718/">test-portal-acceptance-pullrequest(master)#5718</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5718/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/104">liferay-bpm-qa#104</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2037897283">[master] ci:test:relevant - Natanaelbenvindo &gt; liferay-bpm-qa - PR#104 - 2022-11-07[06:35:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/13749/">publish-testray-report#13749</a><br/></div></div>

2022-11-08 13:04 UTC, rafaellajordao commented
ci:forward

2022-11-08 13:04 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-11-08 13:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/1510/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1510/jenkins-report.html">here</a>.</b></p>

2022-11-08 13:08 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2b8bb0c35da088f2763a78b2ecb4604307a6f651">2b8bb0c35da088f2763a78b2ecb4604307a6f651</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Natanaelbenvindo/liferay-portal/tree/LPS-161962">LPS-161962</a><br/>Branch GIT ID: <a href="https://github.com/Natanaelbenvindo/liferay-portal/commit/f45afb7ba09a13c4b48fcdf83b008074a1177c83">f45afb7ba09a13c4b48fcdf83b008074a1177c83</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1319/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1319/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
     [java] SLF4J: Defaulting to no-operation (NOP) logger implementation
     [java] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[stopwatch] [run.batch.test.action: 1:08.967 sec]
     [echo] 
      [get] Getting: http://test-1-36/job/test-portal-source-format/1319//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20221108050759786.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20221108050759786.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null971496079.properties</pre></details></html>

2022-11-08 13:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1319/">test-portal-source-format#1319</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1319/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/104">liferay-bpm-qa#104</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2040135790">[master] ci:test:sf - Natanaelbenvindo &gt; liferay-bpm-qa - PR#104 - 2022-11-08[05:05:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/5278/">publish-testray-report#5278</a><br/></div></div>

2022-11-08 13:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/1510/">test-portal-acceptance-pullrequest(master)#1510</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1510/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/104">liferay-bpm-qa#104</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2040162290">[master] ci:test:relevant - Natanaelbenvindo &gt; liferay-bpm-qa - PR#104 - 2022-11-08[05:05:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/3388/">publish-testray-report#3388</a><br/></div></div>

2022-11-08 13:38 UTC, closed without merging