LPS-193625, LPS-193633 | Test Automation | Master
liferay-bpm-qa/liferay-portal pull request #1047
Opened 2023-08-16 15:15 UTC by andreefarias

Tickets:
* [LPS-193625](https://liferay.atlassian.net/browse/LPS-193625)
* [LPS-193633](https://liferay.atlassian.net/browse/LPS-193633)

2023-08-16 15:16 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-08-16 17:40 UTC, andreefarias commented
ci:test:sf

2023-08-16 17:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/5522/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5522/jenkins-report.html">here</a>.</b></p>

2023-08-16 17:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9e8d478225f67b18d232e4a727e5dad63d3163ad">9e8d478225f67b18d232e4a727e5dad63d3163ad</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LPS-193122">LPS-193122</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/b5c607f42cd5f2ad3981d9aa14b033a077237f9b">b5c607f42cd5f2ad3981d9aa14b033a077237f9b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5522/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5522/jenkins-report.html">here</a>.</h5></details></html>

2023-08-16 17:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5522/">test-portal-source-format#5522</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5522/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1047">liferay-bpm-qa#1047</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2407180065">[master] ci:test:sf - andreefarias &gt; liferay-bpm-qa - PR#1047 - 2023-08-16[10:42:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/20982/">publish-testray-report#20982</a><br/></div></div>

2023-09-26 04:17 UTC, timpak requested changes
@andreefarias please see my comments below. Once we are certain these tests are stable (passing consistently for an entire week), please go back and delete the ignored tests. You can create a ticket to for this task so we don't forget.

Once it's stable for a month or so, we can explore adding the new tests to acceptance.

2023-09-26 04:17 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectAudit.testcase
> +
Let's not include this as an acceptance test until we're sure of the stability of the test.

2023-09-26 04:17 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectAudit.testcase
> +		task ("Given a custom object definition created") {
`Given a custom object definition`

Remember that adjectives go before the noun in English, so the correct phrasing would be `created object definition`

2023-09-26 04:17 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectAudit.testcase
> +		}
Combine this into one task:

`When the user updates and then deletes the object definition`

2023-09-26 04:17 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectAudit.testcase
> +		task ("Then assert that the audit can see the custom object definition created, updated and deleted") {
Combine this into one task:

`Then the Add, Update, and Delete events appear in the Audit records`

2023-09-26 04:17 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectAudit.testcase
> +	@description = "LPS-149508 - Verify CRUD functionality with audit when using object definition"
Verify CRUD events appear in the Audit records for object definitions

2023-09-26 04:17 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectAudit.testcase
> +	@description = "LPS-164582 - Verify CRUD functionality with audit when using object definition entry that has the entry history activated"
Verify CRUD events appear in the Audit records for object entries when entry history is enabled

2023-09-26 04:17 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectAudit.testcase
> +	test AssertCRUDWithObjectDefinition {
AssertCRUDEventsWithObjectDefinition

2023-09-26 04:17 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectAudit.testcase
> +	test AssertCRUDWithObjectEntry {
AssertCRUDEventsWithObjectEntry

2023-09-26 04:17 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectAudit.testcase
> +
Same thing here too, let's not add this to acceptance until we're sure it's stable

2023-09-26 04:17 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectAudit.testcase
> +		task ("Given a custom object definition with toogle for Entry History in Audit Framework activated and a custom field") {
Given a custom object definition with a text field and Entry History enabled

2023-09-26 04:17 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectAudit.testcase
> +		}
Combine this:

`When the user creates, updates, and then deletes an object entry`

2023-09-26 04:17 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectAudit.testcase
> +		task ("Then assert that the audit can see the custom object entry created, updated and deleted") {
Combine this:

`Then the Add, Update, and Delete events appear in the Audit records`

2023-09-27 16:51 UTC, andreefarias commented
ci:test:sf

2023-09-27 16:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/7416/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7416/jenkins-report.html">here</a>.</b></p>

2023-09-27 17:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7416/">test-portal-source-format#7416</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7416/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1047">liferay-bpm-qa#1047</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2432508307">[master] ci:test:sf - andreefarias &gt; liferay-bpm-qa - PR#1047 - 2023-09-27[09:51:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/27665/">publish-testray-report#27665</a><br/></div></div>

2023-10-06 18:44 UTC, closed without merging