LPS-192625
liferay-bpm-qa/liferay-portal pull request #1057
Opened 2023-08-18 15:29 UTC by andreefarias

2023-08-18 15:29 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-08-18 16:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/5631/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5631/jenkins-report.html">here</a>.</b></p>

2023-08-18 16:08 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/48b175497112a99b7f2a12d090b822bd37f03cdc">48b175497112a99b7f2a12d090b822bd37f03cdc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LPS-192625">LPS-192625</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/6859c81e981ea97e0ef483f7de692c80f176b2d3">6859c81e981ea97e0ef483f7de692c80f176b2d3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5631/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5631/jenkins-report.html">here</a>.</h5></details></html>

2023-08-18 16:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5631/">test-portal-source-format#5631</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5631/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1057">liferay-bpm-qa#1057</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2408807054">[master] ci:test:sf - andreefarias &gt; liferay-bpm-qa - PR#1057 - 2023-08-18[09:02:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/21377/">publish-testray-report#21377</a><br/></div></div>

2023-09-26 04:39 UTC, timpak requested changes
@andreefarias please see my comments below

2023-09-26 04:39 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase
> +		task ("When attempting an object entry with incorrect validation") {
When the user attempts to create an invalid object entry

2023-09-26 04:39 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase
> +		task ("Then assert the entry was not added") {
Then the object entry isn't added

2023-09-26 04:39 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase
> +		task ("and When adding the same incorrect object entry before") {
and When the user deactivates the custom validation and attempts to create the same invalid object entry

2023-09-26 04:39 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase
> +		task ("Then assert that the object entry was added on view table") {
Then the object entry is added

2023-09-26 04:39 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase
> +	@description = "LPS-144474 - Verify it's possible to deactivate the custom validation"
Verify an invalid object entry can be added after the validation is deactivated

2023-09-26 04:39 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase
> +	@description = "LPS-144474 - Verify it's possible to add valid entries when define output fields for my validation as full validation"
Verify a valid object entry can be added when the validation is set to full validation

2023-09-26 04:39 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase
> +		property portal.acceptance = "true";
Let's not add this to acceptance yet since we want to ensure the test is stable first

2023-09-26 04:39 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase
> +		task ("Given an custom object definition and a decimal field") {
Given a custom object definition with a decimal field

2023-09-26 04:39 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase
> +		}
We don't need to assert this since the previous test is covering this flow

2023-09-26 04:39 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase
> +		task ("and When a valid object entry") {
When the user creates a valid object entry

2023-09-26 04:39 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase
> +		task ("Then assert that there is only an object entry on view") {
Then the object entry is added

2023-09-26 04:39 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase
> +
We don't need to assert this here since the previous test should cover this

2023-09-26 04:39 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase
> +		task ("and When attempting to add an object entry with an invalid object entry") {
When the user changes the validation logic and attempts to create an invalid object entry

2023-09-26 04:39 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase
> +		}
Turn this into one task:

`Then the invalid object entry isn't added and the existing object entry isn't affected`

2023-10-05 21:21 UTC, andreefarias commented
ci:test:sf

2023-10-05 21:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/4879/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4879/jenkins-report.html">here</a>.</b></p>

2023-10-05 21:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bde9eb760be3e33c3037364b8ecde153eb6678bc">bde9eb760be3e33c3037364b8ecde153eb6678bc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LPS-192625">LPS-192625</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/d6d61cb0747fa49747eb85bd92762c78f25f40a5">d6d61cb0747fa49747eb85bd92762c78f25f40a5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/4879/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4879/jenkins-report.html">here</a>.</h5></details></html>

2023-10-05 21:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/4879/">test-portal-source-format#4879</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4879/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1057">liferay-bpm-qa#1057</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2437209144">[master] ci:test:sf - andreefarias &gt; liferay-bpm-qa - PR#1057 - 2023-10-05[14:22:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/4180/">publish-testray-report#4180</a><br/></div></div>

2023-10-05 21:34 UTC, andreefarias commented
Hey @timpak,

I refactored the testcases after review. So, I'll forward this PR.

2023-10-05 21:35 UTC, andreefarias commented
ci:forward

2023-10-05 21:35 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-10-05 21:35 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2023-10-05 21:36 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-7.liferay.com/job/forward-pullrequest/466//consoleFull)

2023-10-05 21:38 UTC, closed without merging

2023-10-05 21:38 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/141838
[Console](https://test-1-7.liferay.com/job/forward-pullrequest/466//consoleFull)