LPS-172918
liferay-bpm-qa/liferay-portal pull request #1075
Opened 2023-08-28 19:56 UTC by victorhcunha

2023-08-28 19:56 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-08-28 19:56 UTC, victorhcunha commented
ci:test:sf

2023-08-28 20:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/4741/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4741/jenkins-report.html">here</a>.</b></p>

2023-08-28 20:05 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4db9cbc5bff844fb2f99bc044ba3e35ce8aa1d67">4db9cbc5bff844fb2f99bc044ba3e35ce8aa1d67</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/victorhcunha/liferay-portal/tree/LPS-172918">LPS-172918</a><br/>Branch GIT ID: <a href="https://github.com/victorhcunha/liferay-portal/commit/57dfd7f0a113e276285dc34cfc67cbb4db305d7f">57dfd7f0a113e276285dc34cfc67cbb4db305d7f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/4741/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4741/jenkins-report.html">here</a>.</h5></details></html>

2023-08-28 20:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/4741/">test-portal-source-format#4741</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4741/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1075">liferay-bpm-qa#1075</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2414172315">[master] ci:test:sf - victorhcunha &gt; liferay-bpm-qa - PR#1075 - 2023-08-28[13:00:51]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/4041/">publish-testray-report#4041</a><br/></div></div>

2023-09-08 07:50 UTC, timpak requested changes
@victorhcunha please see my comment below

2023-09-08 07:50 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +	@description = "LPS-172918 - Verify that can trigger standalone action for a site scoped object"
Verify the user can trigger a standalone action for a site scoped object

2023-09-08 07:50 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +			ObjectAdmin.addObjectStringFieldEntryViaUI(entryValue = "Entry");
I'm surprised that this works when we don't actually set the panel category key. Nothing to fix here, just an observation

2023-09-26 04:44 UTC, timpak approved these changes
LGTM!

@victorhcunha in the future, if I only request a minor fix from you, you can forward it yourself after completing the revision. It doesn't need to go through me again.

2023-09-26 04:44 UTC, timpak commented
ci:forward

2023-09-26 04:44 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-09-26 04:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1734/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1734/jenkins-report.html">here</a>.</b></p>

2023-09-26 04:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5de5d4cd38c63a2ed1f3915ba71c57a3e4fcef86">5de5d4cd38c63a2ed1f3915ba71c57a3e4fcef86</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/victorhcunha/liferay-portal/tree/LPS-172918">LPS-172918</a><br/>Branch GIT ID: <a href="https://github.com/victorhcunha/liferay-portal/commit/648e481596b28e219a371d4f406be93bccc3fb66">648e481596b28e219a371d4f406be93bccc3fb66</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1734/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1734/jenkins-report.html">here</a>.</h5></details></html>

2023-09-26 04:50 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/1734//consoleFull)

2023-09-26 04:50 UTC, closed without merging

2023-09-26 04:51 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/141285
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/1734//consoleFull)

2023-09-26 05:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/9523/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9523/jenkins-report.html">here</a>.</b></p>

2023-09-26 05:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/9523/">test-portal-acceptance-pullrequest(master)#9523</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9523/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1075">liferay-bpm-qa#1075</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2431160132">[master] ci:test:relevant - victorhcunha &gt; liferay-bpm-qa - PR#1075 - 2023-09-25[22:29:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/22114/">publish-testray-report#22114</a><br/></div></div>

2023-09-26 21:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1734/">test-portal-source-format#1734</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1734/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1075">liferay-bpm-qa#1075</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2431793469">[master] ci:test:sf - victorhcunha &gt; liferay-bpm-qa - PR#1075 - 2023-09-25[21:45:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/6897/">publish-testray-report#6897</a><br/></div></div>