LPS-190807
liferay-bpm-qa/liferay-portal pull request #1088
Opened 2023-09-01 12:55 UTC by JhossephG

https://liferay.atlassian.net/browse/LPS-190807

2023-09-01 12:55 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-01 12:56 UTC, JhossephG commented
ci:test:sf

2023-09-01 12:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/7377/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7377/jenkins-report.html">here</a>.</b></p>

2023-09-01 13:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7377/">test-portal-source-format#7377</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7377/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1088">liferay-bpm-qa#1088</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2417353855">[master] ci:test:sf - JhossephG &gt; liferay-bpm-qa - PR#1088 - 2023-09-01[05:56:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/4509/">publish-testray-report#4509</a><br/></div></div>

2023-09-01 20:40 UTC, timpak requested changes
@JhossephG please see my comments below

2023-09-01 20:40 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectClientExtensions.testcase
> +	@description = "LPS-179367 - Verify CRUD functionality with a created custom object definition using a client extension as the storage type."
Please remove the period since it doesn't follow our existing pattern

2023-09-01 20:40 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectClientExtensions.testcase
> +		property portal.acceptance = "runJhosseph";
Please remove this property and let's monitor it for stability first before adding it to acceptance

2023-09-01 20:40 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectClientExtensions.testcase
> +		task ("Given: Liferay Sample Batch and Liferay Sample Etc Spring Boot are deployed into the current virtual instance") {
Given Liferay Sample Batch and Liferay Sample Etc Spring Boot are deployed to the current virtual instance

2023-09-01 20:40 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectClientExtensions.testcase
> +		task ("Given a custom object stored in a CX proxy storage type published") {
Given a custom object definition with the storage type set to client extension

2023-09-01 20:40 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectClientExtensions.testcase
> +		task ("and Given a text field is created") {
and Given a text field

2023-09-01 20:40 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectClientExtensions.testcase
> +		task ("And then the user is able to create entries") {
Then the user is able to create and read entries

2023-09-01 20:44 UTC, JhossephG commented
ci:test:sf

2023-09-01 20:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-source-format/7088/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7088/jenkins-report.html">here</a>.</b></p>

2023-09-01 20:50 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/86eb502ddbc9137007d87b586098f456e8091fe5">86eb502ddbc9137007d87b586098f456e8091fe5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JhossephG/liferay-portal/tree/LPS-190807">LPS-190807</a><br/>Branch GIT ID: <a href="https://github.com/JhossephG/liferay-portal/commit/90dbb35827dc71ab15a9cf72aa3898352916ae19">90dbb35827dc71ab15a9cf72aa3898352916ae19</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7088/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7088/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: /opt/dev/projects/github/liferay-portal/modules/apps/object/object-test/src/testFunctional/tests/ObjectClientExtensions.testcase expected:&lt;...irtual instance") \{
     [java] []      for (var clientEx...&gt; but was:&lt;...irtual instance") \{
     [java] [
     [java] ]      for (var clientEx...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:457)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
[stopwatch] [run.batch.test.action: 1:52.996 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:504: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:648: Java returned: 1
      [get] Getting: http://test-1-18/job/test-portal-source-format/7088//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230901134954617.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230901134954617.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null882241903.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null785010297
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 197ms
[junitreport] Deleting: /tmp/null785010297
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 09-01-2023 13:49:58:207 PDT
[stopwatch] [run.batch.test.tear.down: 0.001 sec]</pre></details></html>

2023-09-01 20:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7088/">test-portal-source-format#7088</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7088/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1088">liferay-bpm-qa#1088</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2417641329">[master] ci:test:sf - JhossephG &gt; liferay-bpm-qa - PR#1088 - 2023-09-01[13:45:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/4337/">publish-testray-report#4337</a><br/></div></div>

2023-09-04 13:07 UTC, JhossephG commented
ci:test:sf

2023-09-04 13:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1517/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1517/jenkins-report.html">here</a>.</b></p>

2023-09-04 13:11 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f81dc316e4f3f1dcfe5e0865f8c92e365e67b9c5">f81dc316e4f3f1dcfe5e0865f8c92e365e67b9c5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JhossephG/liferay-portal/tree/LPS-190807">LPS-190807</a><br/>Branch GIT ID: <a href="https://github.com/JhossephG/liferay-portal/commit/a8e54e806cd0d10ae27614cd16c7a451a2fccfec">a8e54e806cd0d10ae27614cd16c7a451a2fccfec</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1517/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1517/jenkins-report.html">here</a>.</h5></details></html>

2023-09-05 19:50 UTC, evanilson-santana commented
PR sent [here](https://github.com/liferay-bpm-qa/liferay-portal/pull/1098)

2023-09-05 19:50 UTC, closed without merging