LPS-195232
liferay-bpm-qa/liferay-portal pull request #1100
Opened 2023-09-05 20:58 UTC by mateussandes23

2023-09-05 20:58 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-05 20:59 UTC, mateussandes23 commented
ci:test:sf

2023-09-05 21:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/3917/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3917/jenkins-report.html">here</a>.</b></p>

2023-09-05 21:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2734632486accdb4ef0ea2df712365c77e85932">e2734632486accdb4ef0ea2df712365c77e85932</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-195232">LPS-195232</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/6405251888d864c61ca93908347112c1f2c7d876">6405251888d864c61ca93908347112c1f2c7d876</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/3917/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3917/jenkins-report.html">here</a>.</h5></details></html>

2023-09-05 21:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/3917/">test-portal-source-format#3917</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3917/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1100">liferay-bpm-qa#1100</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2419156486">[master] ci:test:sf - mateussandes23 &gt; liferay-bpm-qa - PR#1100 - 2023-09-05[14:00:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/14610/">publish-testray-report#14610</a><br/></div></div>

2023-10-04 06:26 UTC, timpak requested changes
@mateussandes23 can you break up your changes into separate commits? It's hard for me to understand what changes you're making if you just use one commit for everything. Please talk with @andreefarias if you need examples of what I mean. Also, your commit message contains a spelling mistake.

Some changes I see so far:
- Rename
- Sort
- Wordsmith
- Various logical changes

2023-10-09 13:32 UTC, mateussandes23 commented
Hey @timpak, I was working on those updates and talking with @andreefarias and @Natanaelbenvindo, we remeber that this tests was deleted since that the account restriction field became editable.

2023-10-09 20:31 UTC, closed without merging