LPS-194540
liferay-bpm-qa/liferay-portal pull request #1103
Opened 2023-09-06 20:05 UTC by Luizcarlosqueiroz

2023-09-06 20:06 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-06 21:39 UTC, Luizcarlosqueiroz commented
ci:test:sf

2023-09-06 21:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/3930/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3930/jenkins-report.html">here</a>.</b></p>

2023-09-06 21:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/38dc7c630b1b7df0f92fbe90b9b580fde6e77760">38dc7c630b1b7df0f92fbe90b9b580fde6e77760</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/tree/LPS-194540">LPS-194540</a><br/>Branch GIT ID: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/commit/f51877fffce8a3c43d09b3001902447f2ae70254">f51877fffce8a3c43d09b3001902447f2ae70254</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/3930/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3930/jenkins-report.html">here</a>.</h5></details></html>

2023-09-06 21:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/3930/">test-portal-source-format#3930</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3930/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1103">liferay-bpm-qa#1103</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2419844990">[master] ci:test:sf - Luizcarlosqueiroz &gt; liferay-bpm-qa - PR#1103 - 2023-09-06[14:39:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/14653/">publish-testray-report#14653</a><br/></div></div>

2023-09-08 08:12 UTC, timpak requested changes
Hey @Luizcarlosqueiroz, great job with the new macros! Two minor fixes:
- You don't need a separate commit to create the testcase file, you can include that when you add the first test
- Instead of creating a separate commit to move the macros, just create the macros in a separate file from the beginning

2023-09-08 13:32 UTC, Luizcarlosqueiroz commented
Hey @timpak! Just made the changes :)

2023-09-08 14:01 UTC, Luizcarlosqueiroz commented
So, I noticed that I erased the teardown from my code :sob: 
I'll try do implement again soon, since won't affect this test.

2023-09-12 16:50 UTC, Luizcarlosqueiroz commented
> So, I noticed that I erased the teardown from my code 😭 I'll try do implement again soon, since won't affect this test.

Teardown added :)

2023-10-04 06:32 UTC, timpak requested changes
@Luizcarlosqueiroz please see my comments below, overall really great job! You can forward this once you make your changes.

2023-10-04 06:32 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/macros/ObjectAdmin.macro
> +
I think we can just call the API macro directly instead of wrapping it in another macro.

2023-10-04 06:32 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/macros/ObjectAdmin.macro
> +
We can just call the function directly instead of wrapping it here.

2023-10-04 06:33 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/macros/ObjectAdmin.macro
> +
I think I missed these when I reviewed them the first time 😢

2023-10-17 21:25 UTC, patriciajeanperez commented
Resent here: https://github.com/liferay-bpm-qa/liferay-portal/pull/1175

2023-10-17 21:25 UTC, closed without merging