LPS-192638
liferay-bpm-qa/liferay-portal pull request #1109
Opened 2023-09-12 15:32 UTC by victorhcunha

2023-09-12 15:32 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-12 15:33 UTC, victorhcunha commented
ci:close

2023-09-13 13:46 UTC, victorhcunha commented
ci:open

2023-09-13 13:46 UTC, victorhcunha commented
ci:reopen

2023-09-13 14:15 UTC, victorhcunha commented
ci:test:sf

2023-09-13 14:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/5729/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5729/jenkins-report.html">here</a>.</b></p>

2023-09-13 14:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b38df81fc5a453b2be613fc090870d4ca9befdf0">b38df81fc5a453b2be613fc090870d4ca9befdf0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/victorhcunha/liferay-portal/tree/LPS-192638">LPS-192638</a><br/>Branch GIT ID: <a href="https://github.com/victorhcunha/liferay-portal/commit/dd6ef7990a428d7c5d5bf0a97bc44e4086319157">dd6ef7990a428d7c5d5bf0a97bc44e4086319157</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5729/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5729/jenkins-report.html">here</a>.</h5></details></html>

2023-09-13 14:29 UTC, victorhcunha commented
ci:test:sf

2023-09-13 14:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1628/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1628/jenkins-report.html">here</a>.</b></p>

2023-09-13 14:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b38df81fc5a453b2be613fc090870d4ca9befdf0">b38df81fc5a453b2be613fc090870d4ca9befdf0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/victorhcunha/liferay-portal/tree/LPS-192638">LPS-192638</a><br/>Branch GIT ID: <a href="https://github.com/victorhcunha/liferay-portal/commit/a89095f8b3b6b8e8368361725323a3d57adcba9d">a89095f8b3b6b8e8368361725323a3d57adcba9d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1628/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1628/jenkins-report.html">here</a>.</h5></details></html>

2023-09-13 14:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1628/">test-portal-source-format#1628</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1628/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1109">liferay-bpm-qa#1109</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2423559250">[master] ci:test:sf - victorhcunha &gt; liferay-bpm-qa - PR#1109 - 2023-09-13[07:29:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/6433/">publish-testray-report#6433</a><br/></div></div>

2023-10-04 06:44 UTC, timpak requested changes
@victorhcunha please see my comments below

2023-10-04 06:44 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectPartialValidation.testcase
> +	@description = "LPS-182586 - Verify it's possible to define output fields for my validation as partial validation"
Verify an error message is seen for an invalid field in an object entry if the validation is set to partial validation

2023-10-04 06:44 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectPartialValidation.testcase
> +	test CanAddEntry {
CanValidateField

2023-10-04 06:44 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectPartialValidation.testcase
> +		property portal.acceptance = "true";
Let's not add this to acceptance until we're sure this is stable.

2023-10-04 06:44 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectPartialValidation.testcase
> +		task ("and Given an expression builder to validate if does not contain some numbers and set to partial validation with the precision decimal") {
and Given an expression builder validation set to partial validation with the precision decimal field

2023-10-04 06:44 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectPartialValidation.testcase
> +		task ("When adding an object entry with incorrect validation") {
When the user attempts to create an invalid object entry

2023-10-04 06:44 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectPartialValidation.testcase
> +		task ("Then assert the error message in the object entries layout to the decimal field") {
Then an error message is seen and the object entry isn't added

2023-10-04 06:44 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectPartialValidation.testcase
> +		}
Please include an assertion to verify the entry isn't added

2023-10-19 22:58 UTC, patriciajeanperez commented
ci:forward

2023-10-19 22:58 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-10-19 22:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/11616/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11616/jenkins-report.html">here</a>.</b></p>

2023-10-19 23:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/6833/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6833/jenkins-report.html">here</a>.</b></p>

2023-10-19 23:03 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/25cf442ada2550cfe27a9fd8610c4d5bfb09e289">25cf442ada2550cfe27a9fd8610c4d5bfb09e289</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/victorhcunha/liferay-portal/tree/LPS-192638">LPS-192638</a><br/>Branch GIT ID: <a href="https://github.com/victorhcunha/liferay-portal/commit/5b615dcd0868d27d67373656f1e719133d5995bb">5b615dcd0868d27d67373656f1e719133d5995bb</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/6833/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6833/jenkins-report.html">here</a>.</h5></details></html>

2023-10-19 23:03 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-26.liferay.com/job/test-portal-source-format/6833//consoleFull)

2023-10-19 23:04 UTC, closed without merging

2023-10-19 23:04 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/142476
[Console](https://test-1-26.liferay.com/job/test-portal-source-format/6833//consoleFull)

2023-10-19 23:04 UTC, liferay-continuous-integration commented
This pull request already has open forwarded pull request(s):
https://github.com/brianchandotcom/liferay-portal/pull/142476

Pull request will not be forwarded to `brianchandotcom`.
[Console](https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/11616//consoleFull)

2023-10-19 23:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/6833/">test-portal-source-format#6833</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6833/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1109">liferay-bpm-qa#1109</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2444111700">[master] ci:test:sf - victorhcunha &gt; liferay-bpm-qa - PR#1109 - 2023-10-19[15:58:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/26822/">publish-testray-report#26822</a><br/></div></div>

2023-10-19 23:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/11616/">test-portal-acceptance-pullrequest(master)#11616</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11616/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1109">liferay-bpm-qa#1109</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2444113272">[master] ci:test:relevant - victorhcunha &gt; liferay-bpm-qa - PR#1109 - 2023-10-19[15:58:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/26823/">publish-testray-report#26823</a><br/></div></div>