LPS-195650 - Automation | Objects
liferay-bpm-qa/liferay-portal pull request #1187
Opened 2023-10-23 14:09 UTC by thaiscabrals

Ticket: [LPS-195650](https://liferay.atlassian.net/browse/LPS-195650)
Test: ObjectFolder#CanMoveObjectDefinitionToCurrentFolder

2023-10-23 14:09 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-10-23 14:10 UTC, thaiscabrals commented
ci:test:sf

2023-10-23 14:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/635e1b80858aa3fa264af7df8926cd31445747ec">635e1b80858aa3fa264af7df8926cd31445747ec</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaiscabrals/liferay-portal/tree/LPS-195650">LPS-195650</a><br/>Branch GIT ID: <a href="https://github.com/thaiscabrals/liferay-portal/commit/00292eba25ca0e6e20497f996c5161e348da382b">00292eba25ca0e6e20497f996c5161e348da382b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7215/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7215/jenkins-report.html">here</a>.</h5></details></html>

2023-10-23 14:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7215/">test-portal-source-format#7215</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7215/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1187">liferay-bpm-qa#1187</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2445414577">[master] ci:test:sf - thaiscabrals &gt; liferay-bpm-qa - PR#1187 - 2023-10-23[07:11:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/4466/">publish-testray-report#4466</a><br/></div></div>

2023-10-23 21:34 UTC, patriciajeanperez requested changes
Hey @thaiscabrals, can we rewrite and make sure we are following the steps in https://liferay.atlassian.net/browse/LPS-197996?focusedCommentId=2480396? There should be a "Move to Current Folder" option in the sidebar

2023-10-23 21:34 UTC, patriciajeanperez commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFolder.testcase
> +				locator1 = "ObjectAdmin#SIDEBAR_ITEM");
@thaiscabrals did the test fail without the wait?

2023-10-25 14:00 UTC, thaiscabrals commented
ci:test:sf

2023-10-25 21:06 UTC, thaiscabrals commented
ci:test:sf

2023-10-25 21:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/2473/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2473/jenkins-report.html">here</a>.</b></p>

2023-10-25 21:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1206124b6f7b7d569ceaf75a45f8dffac6ab062f">1206124b6f7b7d569ceaf75a45f8dffac6ab062f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaiscabrals/liferay-portal/tree/LPS-195650">LPS-195650</a><br/>Branch GIT ID: <a href="https://github.com/thaiscabrals/liferay-portal/commit/5b12f8fc9c6f787626820f4013c0d80fc4a1076e">5b12f8fc9c6f787626820f4013c0d80fc4a1076e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-source-format/2473/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2473/jenkins-report.html">here</a>.</h5></details></html>

2023-10-25 21:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/2473/">test-portal-source-format#2473</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2473/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1187">liferay-bpm-qa#1187</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2446725906">[master] ci:test:sf - thaiscabrals &gt; liferay-bpm-qa - PR#1187 - 2023-10-25[14:31:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/10378/">publish-testray-report#10378</a><br/></div></div>

2023-10-30 18:33 UTC, thaiscabrals commented
ci:test:sf

2023-10-30 18:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/2352/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2352/jenkins-report.html">here</a>.</b></p>

2023-10-30 18:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4f33caca1b181bc1a1a7968773ce7447f79449e7">4f33caca1b181bc1a1a7968773ce7447f79449e7</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaiscabrals/liferay-portal/tree/LPS-195650">LPS-195650</a><br/>Branch GIT ID: <a href="https://github.com/thaiscabrals/liferay-portal/commit/a9e56b7c66a94bcbb1b29606aa3092258f52c3a4">a9e56b7c66a94bcbb1b29606aa3092258f52c3a4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2352/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2352/jenkins-report.html">here</a>.</h5></details></html>

2023-10-30 18:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2352/">test-portal-source-format#2352</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2352/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1187">liferay-bpm-qa#1187</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2449250468">[master] ci:test:sf - thaiscabrals &gt; liferay-bpm-qa - PR#1187 - 2023-10-30[11:33:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/10015/">publish-testray-report#10015</a><br/></div></div>

2023-11-07 07:44 UTC, timpak approved these changes
LGTM!

2023-11-07 07:46 UTC, timpak commented
@thaiscabrals can you update the commit message for your last commit? `add` should be capitalized since it's the first word in the commit message. Once you do that, you can forward this.

2023-11-07 14:03 UTC, thaiscabrals commented
ci:test:sf

2023-11-07 14:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/2217/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2217/jenkins-report.html">here</a>.</b></p>

2023-11-07 14:08 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fd0fb0a24b0b7f51f540a472e6ca61ebe7bde0ef">fd0fb0a24b0b7f51f540a472e6ca61ebe7bde0ef</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaiscabrals/liferay-portal/tree/LPS-195650">LPS-195650</a><br/>Branch GIT ID: <a href="https://github.com/thaiscabrals/liferay-portal/commit/d83747916d137c39b222473ce75f4a82bd0e9653">d83747916d137c39b222473ce75f4a82bd0e9653</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/2217/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2217/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found formatting issues:
     [java] At least one commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, FACES, IDE, ISSD, ISSITES, LCD, LHC, LOOP, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin source-formatter.properties in the liferay-portal repository.
     [java]   at com.liferay.source.formatter.util.JIRAUtil.validateJIRAProjectNames(JIRAUtil.java:44)
     [java]   at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1296)
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:327)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:291)
[stopwatch] [run.batch.test.action: 1:47.292 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:504: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:648: Java returned: 1
      [get] Getting: http://test-1-36/job/test-portal-source-format/2217//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20231107060824611.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20231107060824611.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1995143573.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null36404632
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 463ms
[junitreport] Deleting: /tmp/null36404632
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results</pre></details></html>

2023-11-07 14:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/2217/">test-portal-source-format#2217</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2217/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1187">liferay-bpm-qa#1187</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2454067283">[master] ci:test:sf - thaiscabrals &gt; liferay-bpm-qa - PR#1187 - 2023-11-07[06:04:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/9355/">publish-testray-report#9355</a><br/></div></div>

2023-11-07 14:21 UTC, closed without merging

2023-11-07 14:56 UTC, thaiscabrals commented
The test was sent to this [PR](https://github.com/liferay-bpm-qa/liferay-portal/pull/1221).