LPS-195691 - Add ObjectModelBuilder#CanCreateObjectEntry test
liferay-bpm-qa/liferay-portal pull request #1188
Opened 2023-10-23 14:39 UTC by thaiscabrals

2023-10-23 14:39 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-10-23 14:40 UTC, thaiscabrals commented
ci:test:sf

2023-10-23 14:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/5122/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5122/jenkins-report.html">here</a>.</b></p>

2023-10-23 14:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ec9659f8692eda97cc3dc9bdf770ae28cbf2f81c">ec9659f8692eda97cc3dc9bdf770ae28cbf2f81c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaiscabrals/liferay-portal/tree/LPS-195691">LPS-195691</a><br/>Branch GIT ID: <a href="https://github.com/thaiscabrals/liferay-portal/commit/181eee460d6c9ac16966a9ef5f974bf99fcc6b99">181eee460d6c9ac16966a9ef5f974bf99fcc6b99</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5122/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5122/jenkins-report.html">here</a>.</h5></details></html>

2023-10-23 14:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5122/">test-portal-source-format#5122</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5122/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1188">liferay-bpm-qa#1188</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2445427331">[master] ci:test:sf - thaiscabrals &gt; liferay-bpm-qa - PR#1188 - 2023-10-23[07:41:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/19632/">publish-testray-report#19632</a><br/></div></div>

2023-10-25 16:12 UTC, patriciajeanperez commented
Hey @thaiscabrals! Let's interact with the UI instead since this is the test that will cover the creation flow. Other tests can use the API. Thanks!

2023-11-07 07:49 UTC, timpak requested changes
Hey @thaiscabrals can you follow @patriciajeanperez's suggestion and use the UI for the steps instead of the APIs? Since this is going to be our main creation test for Model Builder, we want to ensure the basic flow to create a folder and then create an object definition within the folder is possible. This is a critical use case that's essential to our feature so we have to make sure it works.

2023-11-08 14:28 UTC, closed without merging