LPS-199611
liferay-bpm-qa/liferay-portal pull request #1196
Opened 2023-10-26 16:57 UTC by evanilson-santana

2023-10-26 16:57 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-10-26 16:59 UTC, evanilson-santana commented
ci:test:sf

2023-10-26 17:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-source-format/7327/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/7327/jenkins-report.html">here</a>.</b></p>

2023-10-26 17:08 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/259e93090188cbf1a0ddca3d8d63a4b2d116212e">259e93090188cbf1a0ddca3d8d63a4b2d116212e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LPS-199611">LPS-199611</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/3b3346506b02cd21f5a61147f1fb59c0f0d28134">3b3346506b02cd21f5a61147f1fb59c0f0d28134</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-source-format/7327/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/7327/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: /opt/dev/projects/github/liferay-portal/modules/apps/object/object-test/src/testFunctional/tests/ObjectUpgrade.testcase expected:&lt;...IP_LABEL");
     [java]     \}
     [java]   \}
     [java] 
     [java] [  @priority = 5
     [java]   test ViewPicklistAfterUpgrade7413U33 \{
     [java]     property data.archive.type = "data-archive-object";
     [java]     property database.types = "mariadb,mysql,postgresql,sqlserver";
     [java]     property portal.version = "7.4.13.u33";
     [java] 
     [java]     task ("View a Picklist after Upgrade") \{
     [java]       SetWindowSize.maximizeWindow();
     [java] 
     [java]       Picklist.gotoPicklists();
     [java] 
     [java]       WaitForElementPresent(
     [java]         key_picklistName = "Custom Picklist",
     [java]         locator1 = "Picklist#VIEW_PICKLIST");
     [java] 
     [java]       Picklist.optionsPicklist(
     [java]         menuItem = "View",
     [java]         picklistName = "Custom Picklist");
     [java] 
     [java]       SelectFrame(locator1 = "Picklist#IFRAME_PICKLIST_MODAL");
     [java] 
     [java]       for (var itemNumber : list "1,2,3") \{
     [java]         Picklist.assertPicklistItem(
     [java]           picklistItemKey = "picklistItem\$\{itemNumber\}",
     [java]           picklistItemName = "Picklist Item \$\{itemNumber\}");
     [java]       \}
     [java]     \}
     [java] 
     [java]     task ("Edit a Picklist and items") \{]
     [java]       SelectFrameTop()...&gt; but was:&lt;...IP_LABEL");
     [java]     \}
     [java]   \}
     [java] 
     [java] [
     [java]   @priority = 5
     [java]   test ViewPicklistAfterUpgrade7413U33 \{
     [java]     property data.archive.type = "data-archive-object";
     [java]     property database.types = "mariadb,mysql,postgresql,sqlserver";
     [java]     property portal.version = "7.4.13.u33";
     [java] 
     [java]     task ("View a Picklist after Upgrade") \{
     [java]       SetWindowSize.maximizeWindow();
     [java] 
     [java]       Picklist.gotoPicklists();
     [java] 
     [java]       WaitForElementPresent(
     [java]         key_picklistName = "Custom Picklist",
     [java]         locator1 = "Picklist#VIEW_PICKLIST");
     [java] 
     [java]       Picklist.optionsPicklist(
     [java]         menuItem = "View",
     [java]         picklistName = "Custom Picklist");
     [java] 
     [java]       SelectFrame(locator1 = "Picklist#IFRAME_PICKLIST_MODAL");
     [java] 
     [java]       for (var itemNumber : list "1,2,3") \{
     [java]         Picklist.assertPicklistItem(</pre></details></html>

2023-10-26 17:11 UTC, evanilson-santana commented
ci:test:sf

2023-10-26 17:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-source-format/7327/">test-portal-source-format#7327</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/7327/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1196">liferay-bpm-qa#1196</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2447119855">[master] ci:test:sf - evanilson-santana &gt; liferay-bpm-qa - PR#1196 - 2023-10-26[10:01:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/3514/">publish-testray-report#3514</a><br/></div></div>

2023-10-26 17:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/4946/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4946/jenkins-report.html">here</a>.</b></p>

2023-10-26 17:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/259e93090188cbf1a0ddca3d8d63a4b2d116212e">259e93090188cbf1a0ddca3d8d63a4b2d116212e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LPS-199611">LPS-199611</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/9c2c3167e01bf84320d6491832eb65a23f4ebb1e">9c2c3167e01bf84320d6491832eb65a23f4ebb1e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/4946/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4946/jenkins-report.html">here</a>.</h5></details></html>

2023-10-26 17:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/4946/">test-portal-source-format#4946</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4946/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1196">liferay-bpm-qa#1196</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2447121224">[master] ci:test:sf - evanilson-santana &gt; liferay-bpm-qa - PR#1196 - 2023-10-26[10:12:52]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/4249/">publish-testray-report#4249</a><br/></div></div>

2023-11-07 08:17 UTC, timpak requested changes
@evanilson-santana please see my comment below. Once you address this, you can forward this PR

2023-11-07 08:17 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectUpgrade.testcase
> +		task ("Edit a Picklist and items") {
You added an unnecessary whitespace at the end here

2023-11-07 15:19 UTC, evanilson-santana commented
ci:forward

2023-11-07 15:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/5072/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5072/jenkins-report.html">here</a>.</b></p>

2023-11-07 15:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/2381/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2381/jenkins-report.html">here</a>.</b></p>

2023-11-07 15:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 10 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e1c685eccb815942ce797e6b5614b0a53fa6b9ca">e1c685eccb815942ce797e6b5614b0a53fa6b9ca</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LPS-199611">LPS-199611</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/b54b3620480cc8dce2d3d484871d588d32a3bad9">b54b3620480cc8dce2d3d484871d588d32a3bad9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2381/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2381/jenkins-report.html">here</a>.</h5></details></html>

2023-11-07 15:30 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-33.liferay.com/job/test-portal-source-format/2381//consoleFull)

2023-11-07 15:30 UTC, closed without merging

2023-11-07 15:30 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/143400
[Console](https://test-1-33.liferay.com/job/test-portal-source-format/2381//consoleFull)

2023-11-07 15:30 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 11 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e1c685eccb815942ce797e6b5614b0a53fa6b9ca">e1c685eccb815942ce797e6b5614b0a53fa6b9ca</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1602db437455aac488f8ec3d9d599ea43ae8f4dd">1602db437455aac488f8ec3d9d599ea43ae8f4dd</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2453852354">EE Development Acceptance (master) - 131 - 2023-11-06[16:39:17]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/5072/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5072/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/5072/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2023-11-07 15:31 UTC, liferay-continuous-integration commented
This pull request already has open forwarded pull request(s):
https://github.com/brianchandotcom/liferay-portal/pull/143400

Pull request will not be forwarded to `brianchandotcom`.
[Console](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/5072//consoleFull)

2023-11-07 15:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2381/">test-portal-source-format#2381</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2381/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1196">liferay-bpm-qa#1196</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2454080313">[master] ci:test:sf - evanilson-santana &gt; liferay-bpm-qa - PR#1196 - 2023-11-07[07:19:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/10134/">publish-testray-report#10134</a><br/></div></div>

2023-11-07 15:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/5072/">test-portal-acceptance-pullrequest(master)#5072</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5072/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1196">liferay-bpm-qa#1196</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2454088693">[master] ci:test:relevant - evanilson-santana &gt; liferay-bpm-qa - PR#1196 - 2023-11-07[07:19:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/21151/">publish-testray-report#21151</a><br/></div></div>