LPS-197145
liferay-bpm-qa/liferay-portal pull request #1207
Opened 2023-10-31 20:20 UTC by alanafergs

2023-10-31 20:21 UTC, alanafergs commented
ci:test:sf

2023-11-14 17:37 UTC, patriciajeanperez commented
Hi @alanafergs, I think we should import the exported definitions and not import a new file. If we import a new file, the export and deletion steps of this test wouldn't really matter anymore. There are existing tests in portal where the exported file becomes a temporary file that you can still import in the same test. You can look at `LanguageOverrideExportImport#CanImportExportedPropertiesFile` as an example. Also, please separate your commits as needed rather than sending them all in one commit.

Let me know if you have questions. Thank you!

2023-11-23 21:13 UTC, alanafergs commented
ci:reopen

2023-11-29 18:28 UTC, alanafergs commented
ci:test:sf

2023-11-29 18:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/5078/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/5078/jenkins-report.html">here</a>.</b></p>

2023-11-29 18:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/5078/">test-portal-source-format#5078</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/5078/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1207">liferay-bpm-qa#1207</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2467557705">[master] ci:test:sf - alanafergs &gt; liferay-bpm-qa - PR#1207 - 2023-11-29[10:30:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/4384/">publish-testray-report#4384</a><br/></div></div>

2023-12-02 21:58 UTC, timpak commented
https://github.com/liferay-bpm-qa/liferay-portal/pull/1148 should be ready sometime next week. I'll review this once it's merged.

2023-12-05 18:32 UTC, JhossephG commented
> #1148 should be ready sometime next week. I'll review this once it's merged.

New PR was sent [here](https://github.com/liferay-bpm-qa/liferay-portal/pull/1308)

2023-12-05 18:44 UTC, JhossephG requested changes

2023-12-05 18:44 UTC, JhossephG commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectExportImport.testcase
> +		task ("Then the object definitions are present and the relationship persists") {
Here you should use the macro instead the hard content from it @alanafergs. 
e.g. `ObjectAdmin.openObjectFolder(folderLabel = "Custom Folder");`

2024-03-07 19:03 UTC, closed without merging