LPS-195691 - Add CanCreateObjectEntry test
liferay-bpm-qa/liferay-portal pull request #1226
Opened 2023-11-08 18:55 UTC by thaiscabrals

2023-11-08 18:55 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-11-08 18:56 UTC, thaiscabrals commented
ci:test:sf

2023-11-08 19:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/5024/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5024/jenkins-report.html">here</a>.</b></p>

2023-11-08 19:03 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f511c0d9553cba5a0446d1a63d3f5c128310fb1a">f511c0d9553cba5a0446d1a63d3f5c128310fb1a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaiscabrals/liferay-portal/tree/LPS-195691">LPS-195691</a><br/>Branch GIT ID: <a href="https://github.com/thaiscabrals/liferay-portal/commit/fed15649872086f140e9d2c86b2567a0fbffdf00">fed15649872086f140e9d2c86b2567a0fbffdf00</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5024/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5024/jenkins-report.html">here</a>.</h5></details></html>

2023-11-08 19:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5024/">test-portal-source-format#5024</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5024/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/1226">liferay-bpm-qa#1226</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2455157814">[master] ci:test:sf - thaiscabrals &gt; liferay-bpm-qa - PR#1226 - 2023-11-08[10:57:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/19157/">publish-testray-report#19157</a><br/></div></div>

2023-11-10 13:16 UTC, thaiscabrals commented
This PR was previously reviewed [here](https://github.com/liferay-bpm-qa/liferay-portal/pull/1188).

2023-11-13 23:08 UTC, patriciajeanperez requested changes
Thank you, @thaiscabrals! I have a suggestion for the macro. Please make the necessary changes and rebase.

2023-11-13 23:08 UTC, patriciajeanperez commented on modules/apps/object/object-test/src/testFunctional/macros/ObjectModelBuilder.macro
> +			value1 = ${labelName});
@thaiscabrals Let's do folderName so it's the same with the UI

2023-12-05 19:32 UTC, closed without merging