LRQA-78596
liferay-bpm-qa/liferay-portal pull request #161
Opened 2022-11-23 17:52 UTC by sirfabios

2022-11-23 17:52 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-11-23 17:53 UTC, sirfabios commented
ci:test:sf

2022-11-23 17:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/1265/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1265/jenkins-report.html">here</a>.</b></p>

2022-11-23 17:59 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/eabfcceb98fbe283d925d0c5e321682f14591a4d">eabfcceb98fbe283d925d0c5e321682f14591a4d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/sirfabios/liferay-portal/tree/LRQA-78596">LRQA-78596</a><br/>Branch GIT ID: <a href="https://github.com/sirfabios/liferay-portal/commit/5453655404807a2c0eca1c4981c12424852be778">5453655404807a2c0eca1c4981c12424852be778</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/1265/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1265/jenkins-report.html">here</a>.</h5></details></html>

2022-11-23 18:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/1265/">test-portal-source-format#1265</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1265/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/161">liferay-bpm-qa#161</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2073044081">[master] ci:test:sf - sirfabios &gt; liferay-bpm-qa - PR#161 - 2022-11-23[09:53:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/4182/">publish-testray-report#4182</a><br/></div></div>

2022-12-14 18:47 UTC, evanilson-santana commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-test/src/testFunctional/macros/ProcessBuilderKaleoDesignerReact.macro
> +				value1 = "${script}");
These changes are the same as this: [PR](https://github.com/liferay-bpm-qa/liferay-portal/pull/163/files)

2022-12-14 18:48 UTC, evanilson-santana commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-test/src/testFunctional/macros/ProcessBuilderKaleoDesignerReact.macro
> +			locator1 = "ProcessBuilderKaleoDesignerReact#PROPERTIES_TYPE_TEXTAREA");
The same thing here

2022-12-14 18:49 UTC, evanilson-santana commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-test/src/testFunctional/macros/ProcessBuilderKaleoDesignerReact.macro
> +					value1 = "${script}");
The same thing here

2022-12-14 18:49 UTC, evanilson-santana commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-test/src/testFunctional/paths/ProcessBuilderKaleoDesignerReact.path
> +</tr>
And here

2022-12-14 18:54 UTC, evanilson-santana requested changes
Hey @sirfabios can you combine the changes of this [PR](https://github.com/liferay-bpm-qa/liferay-portal/pull/163) here? You can create two commits for both test fixes.

Please see my comments and let me know if you have any questions.

2022-12-15 15:13 UTC, sirfabios commented
ci:test:sf

2022-12-15 15:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/4010/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4010/jenkins-report.html">here</a>.</b></p>

2022-12-15 15:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/32ef528674387218b1399dec590c5dbec5386b4d">32ef528674387218b1399dec590c5dbec5386b4d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/sirfabios/liferay-portal/tree/LRQA-78596">LRQA-78596</a><br/>Branch GIT ID: <a href="https://github.com/sirfabios/liferay-portal/commit/a3a80f48e09e2bdc71b5b8c22dbab94ab49e19ad">a3a80f48e09e2bdc71b5b8c22dbab94ab49e19ad</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/4010/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4010/jenkins-report.html">here</a>.</h5></details></html>

2022-12-15 15:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/4010/">test-portal-source-format#4010</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4010/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/161">liferay-bpm-qa#161</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2130579946">[master] ci:test:sf - sirfabios &gt; liferay-bpm-qa - PR#161 - 2022-12-15[07:13:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/14703/">publish-testray-report#14703</a><br/></div></div>

2022-12-19 20:14 UTC, andreefarias commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-test/src/testFunctional/tests/ProcessBuilderKaleoDesignerReact.testcase
> -		property portal.upstream = "quarantine";
Hey @sirfabios,

Next time, you can use the property on a different commit.

2022-12-19 20:14 UTC, andreefarias commented on modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-test/src/testFunctional/tests/ProcessBuilderKaleoDesignerReact.testcase
> -		property portal.upstream = "quarantine";
Hey @sirfabios,

Next time, you can use the property on a different commit.

2022-12-19 20:15 UTC, andreefarias commented
ci:forward

2022-12-19 20:15 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-12-19 20:15 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-12-19 20:16 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-37.liferay.com/job/forward-pullrequest/699//consoleFull)

2022-12-19 20:17 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/127889
[Console](https://test-1-37.liferay.com/job/forward-pullrequest/699//consoleFull)

2022-12-19 20:17 UTC, closed without merging