LPS-169427
liferay-bpm-qa/liferay-portal pull request #244
Opened 2022-12-16 16:18 UTC by evanilson-santana

2022-12-16 16:18 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-12-16 16:22 UTC, evanilson-santana commented
For this test case, we need to check if ERC field can use on the Expression Builder. I changed the old validation to a new one. The old validation was `Integer > External Reference Code` that no sense. The new is `customObjectField == externalReferenceCode` were customObjectField is a string field.  This makes sense because ERC field is a string field.

cc: @timpak

2022-12-16 16:29 UTC, evanilson-santana commented
ci:test:sf

2022-12-16 16:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/5205/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5205/jenkins-report.html">here</a>.</b></p>

2022-12-16 16:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7a96bce6142cf30f9b2a02de71aa7e081bc27809">7a96bce6142cf30f9b2a02de71aa7e081bc27809</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LPS-169427">LPS-169427</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/f202b1823fcd45b7f6905e2db0399d3ac351b083">f202b1823fcd45b7f6905e2db0399d3ac351b083</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/5205/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5205/jenkins-report.html">here</a>.</h5></details></html>

2022-12-16 16:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/5205/">test-portal-source-format#5205</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5205/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/244">liferay-bpm-qa#244</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2132039278">[master] ci:test:sf - evanilson-santana &gt; liferay-bpm-qa - PR#244 - 2022-12-16[08:29:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/18637/">publish-testray-report#18637</a><br/></div></div>

2022-12-19 16:48 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> -			ObjectPortlet.viewEntry(entry = "2147483647");
Hey @evanilson-santana,

Add a correct entry with a string field. You need to confirm the correct entry for more precision on testcase.

2022-12-19 17:25 UTC, andreefarias requested changes
Hey @evanilson-santana,

Check my comment and fix the testcase, please. Thanks!

2022-12-19 19:02 UTC, andreefarias commented
ci:forward

2022-12-19 19:02 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-12-19 19:02 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-12-19 19:03 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-38.liferay.com/job/forward-pullrequest/647//consoleFull)

2022-12-19 19:03 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/127885
[Console](https://test-1-38.liferay.com/job/forward-pullrequest/647//consoleFull)

2022-12-19 19:03 UTC, closed without merging