LPS-165992
liferay-bpm-qa/liferay-portal pull request #259
Opened 2022-12-22 13:33 UTC by rafaellajordao

2022-12-22 13:33 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-12-22 13:34 UTC, rafaellajordao commented
ci:test:sf

2022-12-22 13:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/6598/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/6598/jenkins-report.html">here</a>.</b></p>

2022-12-22 13:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/aa708f440f00d3ed3f4b819036b8a8b30b6f2e31">aa708f440f00d3ed3f4b819036b8a8b30b6f2e31</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-165992">LPS-165992</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/926c299788b90f352b49b89be4d3249206b88ebd">926c299788b90f352b49b89be4d3249206b88ebd</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/6598/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/6598/jenkins-report.html">here</a>.</h5></details></html>

2022-12-29 14:36 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +				pluralLabelName = "Custom Objects 161891");
Use the ticket number correct to add the Custom Object - [LPS-165992](https://issues.liferay.com/browse/LPS-165992)

2022-12-29 14:36 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +				objectName_1 = "CustomObject161891",
Also too - [LPS-165992](https://issues.liferay.com/browse/LPS-165992)

2022-12-29 14:37 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +			ObjectAdmin.publishObjectViaAPI(objectName = "CustomObject161891");
Also too - [LPS-165992](https://issues.liferay.com/browse/LPS-165992)

2022-12-29 14:37 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +			ObjectPortlet.selectCustomObject(label = "Custom Object 161891");
Also too - [LPS-165992](https://issues.liferay.com/browse/LPS-165992)

2022-12-29 14:37 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +				objectName = "CustomObject161891",
Also too - [LPS-165992](https://issues.liferay.com/browse/LPS-165992)

2022-12-29 14:37 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +			ObjectAdmin.goToCustomObject(objectName = "CustomObject161891");
Also too - [LPS-165992](https://issues.liferay.com/browse/LPS-165992)

2022-12-29 14:38 UTC, andreefarias requested changes
Hi @rafaellajordao,

The testcases were well written. Added some comments to avoid CI errors. Check and fix it. Thanks!

2023-01-03 15:15 UTC, rafaellajordao commented
conflict resolved in this [PR#279](https://github.com/liferay-bpm-qa/liferay-portal/pull/279)

2023-01-03 15:15 UTC, closed without merging