LPS-162194
liferay-bpm-qa/liferay-portal pull request #260
Opened 2022-12-22 13:58 UTC by rafaellajordao

2022-12-22 13:59 UTC, rafaellajordao commented
ci:test:sf

2022-12-22 14:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/4020/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4020/jenkins-report.html">here</a>.</b></p>

2022-12-29 14:40 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +				pluralLabelName = "Custom Objects 151573");
Use the ticket number correct to add the Custom Object - [LPS-162194](https://issues.liferay.com/browse/LPS-162194)

2022-12-29 14:40 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +				objectName = "CustomObject151573");
Also too - [LPS-162194](https://issues.liferay.com/browse/LPS-162194)

2022-12-29 14:41 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +				objectLabel = "Custom Object 151573",
Also too - [LPS-162194](https://issues.liferay.com/browse/LPS-162194)

2022-12-29 14:41 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +			ObjectAdmin.goToCustomObject(objectName = "CustomObject151573");
Also too - [LPS-162194](https://issues.liferay.com/browse/LPS-162194)

2022-12-29 14:41 UTC, andreefarias requested changes
Hi @rafaellajordao,

The testcases were well written. Added some comments to avoid CI errors. Check and fix it. Thanks!

2023-01-03 15:15 UTC, rafaellajordao commented
conflict resolved in this https://github.com/liferay-bpm-qa/liferay-portal/pull/279

2023-01-03 15:15 UTC, closed without merging