LPS-165980
liferay-bpm-qa/liferay-portal pull request #267
Opened 2022-12-27 14:50 UTC by rafaellajordao

2022-12-27 14:51 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-12-27 14:51 UTC, rafaellajordao commented
ci:test:sf

2022-12-27 14:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/5876/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/5876/jenkins-report.html">here</a>.</b></p>

2022-12-27 14:59 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dcbf9da3c0fa0ec1807b923f76fe15e7f579b19c">dcbf9da3c0fa0ec1807b923f76fe15e7f579b19c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-165980">LPS-165980</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/361101876fa847dcc93b78e8815e84babca6ddcf">361101876fa847dcc93b78e8815e84babca6ddcf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/5876/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/5876/jenkins-report.html">here</a>.</h5></details></html>

2022-12-27 15:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-source-format/5876/">test-portal-source-format#5876</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/5876/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/267">liferay-bpm-qa#267</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2145032948">[master] ci:test:sf - rafaellajordao &gt; liferay-bpm-qa - PR#267 - 2022-12-27[06:55:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/2848/">publish-testray-report#2848</a><br/></div></div>

2022-12-29 13:54 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +				pluralLabelName = "Custom Objects 161898");
Use the ticket number correct to add the Custom Object - [LPS-165980](https://issues.liferay.com/browse/LPS-165980)

2022-12-29 13:55 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +			ObjectAdmin.goToCustomObject(objectName = "CustomObject161898");
Also too - [LPS-165980](https://issues.liferay.com/browse/LPS-165980)

2022-12-29 13:57 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +			Button.clickSave();
Change `Button.clickSave();` to `PortletEntry.save();`

> The PortletEntry macros wait for JS events to fire before moving forward in the test. Without waiting, test assets sometimes aren't added properly leading to failed assertions.

2022-12-29 13:58 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +				pluralLabelName = "Custom Objects 161899");
Use the ticket number correct to add the Custom Object - [LPS-165981](https://issues.liferay.com/browse/LPS-165981)

2022-12-29 13:59 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +			ObjectPortlet.selectCustomObject(label = "Custom Object 161899");
Also too - [LPS-165981](https://issues.liferay.com/browse/LPS-165981)

2022-12-29 13:59 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +			ObjectAdmin.goToCustomObject(objectName = "CustomObject161899");
Also too - [LPS-165981](https://issues.liferay.com/browse/LPS-165981)

2022-12-29 14:00 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +			ObjectPortlet.selectCustomObject(label = "Custom Object 161898");
Also too - [LPS-165980](https://issues.liferay.com/browse/LPS-165980)

2022-12-29 14:01 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +			Button.clickSave();
Change `Button.clickSave();` to `PortletEntry.save();`

> The PortletEntry macros wait for JS events to fire before moving forward in the test. Without waiting, test assets sometimes aren't added properly leading to failed assertions.

2022-12-29 14:10 UTC, andreefarias requested changes
Hi @rafaellajordao,

The testcases were well written. Added some comments to avoid CI errors. Check and fix it. Thanks!

2023-01-03 15:15 UTC, rafaellajordao commented
conflict resolved in this https://github.com/liferay-bpm-qa/liferay-portal/pull/279

2023-01-03 15:15 UTC, closed without merging