LPS-171861 Automate ObjectActions#CanCreateActionAddObjectEntryWithOnOrderStatusUpdate
liferay-bpm-qa/liferay-portal pull request #285
Opened 2023-01-04 19:28 UTC by thaiscabrals

2023-01-04 19:28 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-01-04 19:30 UTC, thaiscabrals commented
ci:test:sf

2023-01-04 19:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/4386/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4386/jenkins-report.html">here</a>.</b></p>

2023-01-04 19:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/615f7d1bb15b9bb39be46931531e0b1f2fd883fa">615f7d1bb15b9bb39be46931531e0b1f2fd883fa</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaiscabrals/liferay-portal/tree/LPS-171861">LPS-171861</a><br/>Branch GIT ID: <a href="https://github.com/thaiscabrals/liferay-portal/commit/57efa5927fcdbe23f2cc7025c3ab530540946313">57efa5927fcdbe23f2cc7025c3ab530540946313</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/4386/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4386/jenkins-report.html">here</a>.</h5></details></html>

2023-01-04 19:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/4386/">test-portal-source-format#4386</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4386/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/285">liferay-bpm-qa#285</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2149622682">[master] ci:test:sf - thaiscabrals &gt; liferay-bpm-qa - PR#285 - 2023-01-04[11:30:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/16414/">publish-testray-report#16414</a><br/></div></div>

2023-01-04 21:06 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +	@description = "Verify it's possible to add an object entry with the trigger On Order Status Update"
On the description, add the story ticket.

2023-01-04 21:10 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				pluralLabelName = "Custom Objects");
Use the testcase ticket to complement the object name.

Ex.
```
ObjectAdmin.addObjectViaAPI(
        labelName = "Custom Object 171861",
	objectName = "CustomObject171861",
	pluralLabelName = "Custom Objects 171861");
```

Remember to replace all object names

2023-01-04 21:13 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		task ("Then the action is triggered") {
Use `"Then the action is triggered on Object entries"` because exemplifies better where is the action.

2023-01-04 21:15 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				whenAction = "On Order Status Update");
Move it to the `Given` task

2023-01-04 21:18 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		task ("Given an action in the Commerce Order object") {
Use "Given an action in the Commerce Order triggered with Custom Object" because exemplifies better what is given to.

2023-01-04 21:21 UTC, andreefarias requested changes
Good work! I requested small changes to better the legibility of the code.

2023-01-04 21:23 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +			Navigator.openURL();
You can remove it.

The `ObjectAdmin.goToCustomObject(objectName = "CustomObject");` works via URL, so not is necessary to go home page.

2023-01-05 14:44 UTC, closed without merging

2023-01-05 14:45 UTC, thaiscabrals commented
ci:reopen

2023-01-05 14:54 UTC, thaiscabrals commented
ci:close