LPS-171913
liferay-bpm-qa/liferay-portal pull request #338
Opened 2023-01-20 19:52 UTC by davisaints

2023-01-20 19:52 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-01-20 19:55 UTC, davisaints commented
ci:test:sf

2023-01-20 19:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/4579/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4579/jenkins-report.html">here</a>.</b></p>

2023-01-20 19:59 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/347d0d9e32ce975c2f9ac0cc6070b73ebb1a50c2">347d0d9e32ce975c2f9ac0cc6070b73ebb1a50c2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/davisaints/liferay-portal/tree/LPS-171913">LPS-171913</a><br/>Branch GIT ID: <a href="https://github.com/davisaints/liferay-portal/commit/6881ad864967c48c17705e9a864505a1bd0ec062">6881ad864967c48c17705e9a864505a1bd0ec062</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/4579/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4579/jenkins-report.html">here</a>.</h5></details></html>

2023-01-20 20:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/4579/">test-portal-source-format#4579</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4579/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/338">liferay-bpm-qa#338</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2168209647">[master] ci:test:sf - davisaints &gt; liferay-bpm-qa - PR#338 - 2023-01-20[11:55:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/17237/">publish-testray-report#17237</a><br/></div></div>

2023-01-25 17:23 UTC, davisaints commented
ci:test:sf

2023-01-25 17:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/4053/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4053/jenkins-report.html">here</a>.</b></p>

2023-01-25 17:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dc146fb13acb8f3ede19559bff019a203cd50635">dc146fb13acb8f3ede19559bff019a203cd50635</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/davisaints/liferay-portal/tree/LPS-171913">LPS-171913</a><br/>Branch GIT ID: <a href="https://github.com/davisaints/liferay-portal/commit/d1ddeef2bface332ddfcfc9a73a34c3ca7996ada">d1ddeef2bface332ddfcfc9a73a34c3ca7996ada</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/4053/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4053/jenkins-report.html">here</a>.</h5></details></html>

2023-01-27 21:10 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				pluralLabelName = "Custom Objects");
You can use LPS when adding a Custom Object, this way avoid inconsistencies in the CI
```
ObjectAdmin.addObjectViaAPI(
	labelName = "Custom Object 171913",
	objectName = "CustomObject171913",
	pluralLabelName = "Custom Objects 171913");
```

2023-01-27 21:11 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				objectName = "CustomObject");
Remember to replace all of them.

2023-01-27 21:15 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				portlet = "Custom Objects");
You can use macro via API here

`ObjectAdmin.goToCustomObject(objectName = "CustomObject171913");`

2023-01-27 21:16 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				objectName = "CustomObject");
Remember to replace all of them.

2023-01-27 21:17 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				objectName = "CustomObject");
Remember to replace all of them.

`objectName = "CustomObject");` to `objectName = "CustomObject171913");`

2023-01-27 21:24 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +			Refresh();
I believe that it's more useful in testcase:

```
Button.click(button = "Submit");

Alert.viewSuccessMessage();
```

2023-01-27 21:25 UTC, andreefarias requested changes
Hey @davisaints,

Good job with this test. I request only some small changes! Thanks!

2023-01-30 13:04 UTC, davisaints commented
ci:test:sf

2023-01-30 13:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/3773/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3773/jenkins-report.html">here</a>.</b></p>

2023-01-30 13:07 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/569300c7313c5ce484a3b6d2868dc36520149c7e">569300c7313c5ce484a3b6d2868dc36520149c7e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/davisaints/liferay-portal/tree/LPS-171913">LPS-171913</a><br/>Branch GIT ID: <a href="https://github.com/davisaints/liferay-portal/commit/8870b8a2969936e507c13aef5312d7649a822888">8870b8a2969936e507c13aef5312d7649a822888</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/3773/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3773/jenkins-report.html">here</a>.</h5></details></html>

2023-01-30 13:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/3773/">test-portal-source-format#3773</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3773/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/338">liferay-bpm-qa#338</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2180189533">[master] ci:test:sf - davisaints &gt; liferay-bpm-qa - PR#338 - 2023-01-30[05:04:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/13300/">publish-testray-report#13300</a><br/></div></div>

2023-02-01 22:13 UTC, andreefarias approved these changes

2023-02-01 22:14 UTC, andreefarias commented
Looks good to me! 🎉

2023-02-06 13:08 UTC, evanilson-santana commented
ci:forward

2023-02-07 08:36 UTC, timpak requested changes
Hey @davisaints, good job with this test, it's pretty complex! Can you take a look at my comments and get back to me? The wording needs to be updated for the first When.

For the other two, take a look at the Commerce tests and see how their tests are executing these steps. If they don't have macros, that's fine. If they do, we should try and use them as long as it makes sense for the test.

2023-02-07 08:36 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		task ("When: The user adds something to the cart and submits the order") {
`The user adds an item to the cart and submits the order`

Just wanted to be a little more specific here

2023-02-07 08:36 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +			Alert.viewSuccessMessage();
Same thing here, is there not a macro for this or at least some of it?

2023-02-07 12:41 UTC, davisaints commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +			Click(locator1 = "Button#CONTINUE");
For this I found. Changes being made...

2023-02-08 13:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/3640/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3640/jenkins-report.html">here</a>.</b></p>

2023-02-08 13:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6005c85e2ecc68aa2d02852902b1c6794ad83fad">6005c85e2ecc68aa2d02852902b1c6794ad83fad</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/davisaints/liferay-portal/tree/LPS-171913">LPS-171913</a><br/>Branch GIT ID: <a href="https://github.com/davisaints/liferay-portal/commit/b72066fe1670c3318d3b1e252259a55aa2b4ecfc">b72066fe1670c3318d3b1e252259a55aa2b4ecfc</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/3640/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3640/jenkins-report.html">here</a>.</h5></details></html>

2023-02-08 13:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/3640/">test-portal-source-format#3640</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3640/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/338">liferay-bpm-qa#338</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2189665573">[master] ci:test:sf - davisaints &gt; liferay-bpm-qa - PR#338 - 2023-02-08[05:17:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/13617/">publish-testray-report#13617</a><br/></div></div>

2023-02-08 14:18 UTC, davisaints commented
ci:test:sf

2023-02-08 14:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/4140/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4140/jenkins-report.html">here</a>.</b></p>

2023-02-08 14:22 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6005c85e2ecc68aa2d02852902b1c6794ad83fad">6005c85e2ecc68aa2d02852902b1c6794ad83fad</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/davisaints/liferay-portal/tree/LPS-171913">LPS-171913</a><br/>Branch GIT ID: <a href="https://github.com/davisaints/liferay-portal/commit/5ffb83e54d5dd659919fea624b179ca8ac94441c">5ffb83e54d5dd659919fea624b179ca8ac94441c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/4140/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4140/jenkins-report.html">here</a>.</h5></details></html>

2023-02-08 14:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/4140/">test-portal-source-format#4140</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4140/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/338">liferay-bpm-qa#338</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2189744595">[master] ci:test:sf - davisaints &gt; liferay-bpm-qa - PR#338 - 2023-02-08[06:19:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/15170/">publish-testray-report#15170</a><br/></div></div>

2023-02-10 12:10 UTC, davisaints commented
ci:test:sf

2023-02-10 12:14 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ae403c678eca01bfcf819db7b9b156d1f1cdd957">ae403c678eca01bfcf819db7b9b156d1f1cdd957</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/davisaints/liferay-portal/tree/LPS-171913">LPS-171913</a><br/>Branch GIT ID: <a href="https://github.com/davisaints/liferay-portal/commit/09e97334c9b992eb02d964064e273defe916b1a8">09e97334c9b992eb02d964064e273defe916b1a8</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/5212/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5212/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase expected:&lt;...pdate"
     [java]   @priority = [4
     [java]   test CanCreateActionAddObjectEntryWithOnPaymentStatusUpdate \{
     [java]     task ("Given: An object with a field is created") \{
     [java]       ObjectAdmin.addObjectViaAPI(
     [java]         labelName = "Custom Object 171913",
     [java]         objectName = "CustomObject171913",
     [java]         pluralLabelName = "Custom Objects 171913");
     [java] 
     [java]       ObjectAdmin.addObjectFieldViaAPI(
     [java]         fieldBusinessType = "Text",
     [java]         fieldLabelName = "Custom Field",
     [java]         fieldName = "customObjectField",
     [java]         fieldType = "String",
     [java]         isRequired = "true",
     [java]         objectName = "CustomObject171913");
     [java] 
     [java]       ObjectAdmin.publishObjectViaAPI(objectName = "CustomObject171913");
     [java]     \}
     [java] 
     [java]     task ("And given: An Action is created") \{
     [java]       ObjectAdmin.openObjectAdmin();
     [java] 
     [java]       ObjectPortlet.selectCustomObject(label = "Commerce Order");
     [java] 
     [java]       ObjectAdmin.goToActionsTab();
     [java] 
     [java]       ObjectAdmin.addObjectActionViaUI(
     [java]         actionLabel = "Custom Action",
     [java]         active = "true",
     [java]         inputMethod = "true",
     [java]         inputValue = "Action shot on add",
     [java]         objectLabel = "Custom Object 171913",
     [java]         thenAction = "Add an Object Entry",
     [java]         whenAction = "On Payment Status Update");
     [java]     \}
     [java] 
     [java]     task ("And given: An account, minium site and an order is created") \{
     [java]       CommerceAccelerators.initializeNewSiteViaAccelerator(siteName = "Minium");
     [java] 
     [java]       ApplicationsMenu.gotoSite(site = "Minium");
     [java] 
     [java]       JSONAccountEntry.addAccountEntry(
     [java]         accountEntryName = "Accounts Name",
     [java]         accountEntryType = "Business");
     [java] 
     [java]       FrontStore.addInitializerProductToCart(
     [java]         productName = "U-Joint",
     [java]         productQuantity = 1);
     [java] 
     [java]       Refresh();
     [java] 
     [java]       CommerceCheckout.gotoCheckout();
     [java] 
     [java]       CommerceCheckout.initializersCheckout(
     [java]         newAddressAddress = "Test Address",</pre></details></html>

2023-02-10 12:50 UTC, davisaints commented
ci:test:sf

2023-02-10 12:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/5212/">test-portal-source-format#5212</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5212/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/338">liferay-bpm-qa#338</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2192779911">[master] ci:test:sf - davisaints &gt; liferay-bpm-qa - PR#338 - 2023-02-10[04:10:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/20058/">publish-testray-report#20058</a><br/></div></div>

2023-02-10 13:23 UTC, davisaints commented
ci:test:sf

2023-02-10 13:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/1619/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1619/jenkins-report.html">here</a>.</b></p>

2023-02-10 13:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d48b4c356269b67c7c07fc44abf49cc4377b51b4">d48b4c356269b67c7c07fc44abf49cc4377b51b4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/davisaints/liferay-portal/tree/LPS-171913">LPS-171913</a><br/>Branch GIT ID: <a href="https://github.com/davisaints/liferay-portal/commit/8029be9de533ae72167db84bd45407cb9c6cd8aa">8029be9de533ae72167db84bd45407cb9c6cd8aa</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1619/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1619/jenkins-report.html">here</a>.</h5></details></html>

2023-02-10 13:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1619/">test-portal-source-format#1619</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1619/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/338">liferay-bpm-qa#338</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2192791528">[master] ci:test:sf - davisaints &gt; liferay-bpm-qa - PR#338 - 2023-02-10[05:24:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/6541/">publish-testray-report#6541</a><br/></div></div>

2023-02-10 13:33 UTC, davisaints commented
> Hey @davisaints, good job with this test, it's pretty complex! Can you take a look at my comments and get back to me? The wording needs to be updated for the first When.
> 
> For the other two, take a look at the Commerce tests and see how their tests are executing these steps. If they don't have macros, that's fine. If they do, we should try and use them as long as it makes sense for the test.

Hey @timpak! The changes were made and the delay in submitting for review was a bug involving actions (which has since been fixed). And an observation is that I didn't find the macros in Commerce, but I still managed to simplify this test.

2023-02-10 13:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/6658/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/6658/jenkins-report.html">here</a>.</b></p>

2023-02-10 13:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d48b4c356269b67c7c07fc44abf49cc4377b51b4">d48b4c356269b67c7c07fc44abf49cc4377b51b4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/davisaints/liferay-portal/tree/LPS-171913">LPS-171913</a><br/>Branch GIT ID: <a href="https://github.com/davisaints/liferay-portal/commit/8029be9de533ae72167db84bd45407cb9c6cd8aa">8029be9de533ae72167db84bd45407cb9c6cd8aa</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/6658/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/6658/jenkins-report.html">here</a>.</h5></details></html>

2023-02-10 13:41 UTC, davisaints commented
> Hey @davisaints, good job with this test, it's pretty complex! Can you take a look at my comments and get back to me? The wording needs to be updated for the first When.
> 
> For the other two, take a look at the Commerce tests and see how their tests are executing these steps. If they don't have macros, that's fine. If they do, we should try and use them as long as it makes sense for the test.

Hey @timpak! The changes were made and the delay in submitting for review was a bug involving actions (which has since been fixed). And an observation is that I didn't find the macros in Commerce, but I still managed to simplify this test.

2023-02-10 15:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-19.liferay.com/job/test-portal-source-format/6658/">test-portal-source-format#6658</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/6658/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/338">liferay-bpm-qa#338</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2192868227">[master] ci:test:sf - davisaints &gt; liferay-bpm-qa - PR#338 - 2023-02-10[05:34:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-19.liferay.com/job/publish-testray-report/3187/">publish-testray-report#3187</a><br/></div></div>

2023-02-21 19:21 UTC, epark18 commented
ci:test:sf

2023-02-21 19:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/4954/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4954/jenkins-report.html">here</a>.</b></p>

2023-02-21 19:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5f5176fa8aca7b02462143fd4af2e97fba4ec30d">5f5176fa8aca7b02462143fd4af2e97fba4ec30d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/davisaints/liferay-portal/tree/LPS-171913">LPS-171913</a><br/>Branch GIT ID: <a href="https://github.com/davisaints/liferay-portal/commit/8029be9de533ae72167db84bd45407cb9c6cd8aa">8029be9de533ae72167db84bd45407cb9c6cd8aa</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/4954/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4954/jenkins-report.html">here</a>.</h5></details></html>

2023-02-22 05:59 UTC, epark18 commented
@davisaints This looks good to me! I resent here https://github.com/liferay-bpm-qa/liferay-portal/pull/483 with some very minor typo fixes.

2023-02-22 05:59 UTC, closed without merging