LPS-163069 | Test Automation
liferay-bpm-qa/liferay-portal pull request #341
Opened 2023-01-23 20:12 UTC by Luizcarlosqueiroz

2023-01-23 20:12 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-01-23 20:13 UTC, Luizcarlosqueiroz commented
ci:test:sf

2023-01-23 20:13 UTC, Luizcarlosqueiroz commented
ci:test:objects

2023-01-23 20:14 UTC, liferay-continuous-integration commented
The test suite specified is not a valid test suite.
Please refer to the available test suites below.
#### ci:test[:suite][:SHA|nocompile|norebase|gist-SHA]
&nbsp;&nbsp;&nbsp;&nbsp;Test the pull request. Optionally specify the name of the test suite and/or optionally specify the upstream SHA to test against or use "nocompile" to test with a prebuilt bundle or use "norebase" to test without rebasing.
<details><summary><strong>Available test suites:</strong></summary>

- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance** - Test acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-functional** - Test acceptance functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-functional-db-partition** - Test acceptance functional tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-release** - Compile a release bundle and execute acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-upstream** - Test acceptance upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**account** - Test Account tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud** - Test Analytics Cloud tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud-acceptance** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud-quarantine** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**app-servers** - Test Deployments on App Servers.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**auto-tagging** - Test Auto Tagging tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend** - Test backend tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend-hypersonic** - Test backend tests on Hypersonic.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blade** - Test Blade samples tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blogs** - Test Blogs tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bulk-editing** - Test Bulk Editing tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bundle** - Saves a compiled tomcat bundle.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**calendar** - Test Calendar tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**click-to-chat** - Test Click to Chat tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**clustering** - Test clustering tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**comment** - Test Comment tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce** - Test only Commerce tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-database** - Test only Commerce Database tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-es7-remote** - Test only Commerce tests with the latest compatible remote Elasticsearch 7 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-functional** - Test only Commerce functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**content-page-review** - Test Content Page Review (comments) tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**continuous-integration** - Test Continuous Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**cookies** - Test Cookie Preferences tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-engine** - Test Data Engine functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-integration** - Test only Data Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-integration-functional** - Test only functional Data Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**db-partition** - Test Database Partitioning functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**depot** - Test Depot tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**digital-signature** - Test Digital Signature tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dl-store** - Test Document Library Store tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**document** - Test Document and Media tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**drools** - Test Drools tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dummy** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo** - Test all Echo (WCM) team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-acceptance** - Test Echo (WCM) team acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-db-partition** - Test Echo (WCM) team acceptance tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-headless** - Test Echo (WCM) team headless components.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-upgrade** - Test Echo (WCM) team upgrade tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**environments** - Test environment acceptance functional tests on all available environment stacks.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**export-import** - Test exportimport tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms** - Test forms tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms-functional** - Test only functional forms tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**friendly-url** - Test Friendly URL tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend** - Test all Frontend Infra team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-clay** - Test Frontend Infra team Clay tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-data-set** - Test frontend data set tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-dev-exp** - Test frontend developer experience tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-remote-apps** - Test frontend remote apps tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-ui** - Test frontend ui tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-walkthrough** - Test frontend walkthrough tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet** - Test upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet-bucket** - Test a subset of upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gradle-plugins** - Test Gradle Plugins tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless** - Test all headless team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-acceptance** - Test headless team acceptance tests considering Headless and Rest Builder.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-functional** - Headless Team functional API tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**item-selector** - Test item selector tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**jdk11** - Test acceptance, smoke, and upgrade functional tests against JDK11.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**jsf** - Test Liferay Faces tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**kaleo-forms** - Test Kaleo Forms admin tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**knowledge-base** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**ldap** - Test LDAP tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**license** - Compile a release bundle and execute tests for licensing.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**license-cluster** - Compile a release bundle and execute tests for cluster licensing on 32GB slaves.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**liferay-online** - Compile a release bundle and execute tests with liferay online properties.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lima** - Test Lima tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lima-acceptance** - Test Lima acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lima-db-partition** - Test Lima functional tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lima-upgrade** - Test Lima upgrade tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lpkg** - Test LPKG tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**message-boards** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**mfa** - Test Multi Factor Authentication tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**notifications** - Test Notifications tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**oauth2** - Test OAuth 2 tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**object** - Test Object tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**oidc** - Test OpenID Connect tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**onedrive** - Test OneDrive tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**online-editing** - Test Online Editing tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**osb-site-initializer-customer-portal** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**osb-site-initializer-partner-portal** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**passwor [...]

2023-01-23 20:17 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/94e9be42d7129d3e8a627cf0e87596683a7cef75">94e9be42d7129d3e8a627cf0e87596683a7cef75</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/tree/LPS-163069-Automation">LPS-163069-Automation</a><br/>Branch GIT ID: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/commit/897d46fb586b9b081d3fa0274a92009173f42811">897d46fb586b9b081d3fa0274a92009173f42811</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/4553/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4553/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Truncated message :
     [java] ./modules/apps/object/object-test/src/testFunctional/tests/Object.testcase expected:&lt;...\}
     [java] 
     [java]   @description = "[LPS-150886 - Verify that it's possible to delete an object after deleting the relationship"
     [java]   @priority = "4"
     [java]   test CanDeleteCustomObjectAfterDeleteRelationship \{
     [java]     ObjectAdmin.addObjectViaAPI(
     [java]       labelName = "Custom Object 290",
     [java]       objectName = "CustomObject290",
     [java]       pluralLabelName = "Custom Objects 290");
     [java] 
     [java]     ObjectAdmin.addObjectFieldViaAPI(
     [java]       fieldBusinessType = "Text",
     [java]       fieldLabelName = "Custom Field",
     [java]       fieldName = "customObjectField",
     [java]       fieldType = "String",
     [java]       isRequired = "false",
     [java]       objectName = "CustomObject290");
     [java] 
     [java]     ObjectAdmin.addObjectRelationshipViaAPI(
     [java]       objectName_1 = "CustomObject290",
     [java]       objectName_2 = "User",
     [java]       relationshipLabel = "Relationship",
     [java]       relationshipName = "relationship",
     [java]       relationshipType = "oneToMany");
     [java] 
     [java]     ObjectAdmin.publishObjectViaAPI(objectName = "CustomObject290");
     [java] 
     [java]     ObjectAdmin.openObjectAdmin();
     [java] 
     [java]     Click(
     [java]       key_objectLabel = "Custom Object 290",
     [java]       locator1 = "ObjectAdmin#OBJECT_KEBAB_MENU");
     [java] 
     [java]     MenuItem.clickNoError(menuItem = "Delete");
     [java] 
     [java]     SelectFrame(locator1 = "ObjectCustomViews#VIEW_MODAL_CONTENT");
     [java] 
     [java]     ObjectAdmin.assertCannotDeleteObjectWithRelationshipErrorMessage();
     [java] 
     [java]     ObjectAdmin.openObjectAdmin();
     [java] 
     [java]     ObjectPortlet.selectSystemObject(label = "Custom Object 290");
     [java] 
     [java]     ObjectAdmin.gotoRelationshipsTab();
     [java] 
     [java]     ObjectAdmin.deleteRelationshipViaUI(
     [java]       relationshipLabel = "Relationship",
     [java]       relationshipName = "relationship");
     [java] 
     [java]     ObjectAdmin.openObjectAdmin();
     [java] 
     [java]     ObjectAdmin.deleteCustomObjectViaUI(
     [java]       labelName = "Custom Object 290",
     [java]       objectName = "CustomObject290");
     [java] 
     [java]     AssertElementNotPresent(</pre></details></html>

2023-01-23 20:22 UTC, Luizcarlosqueiroz commented
ci:test:sf

2023-01-23 20:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/4553/">test-portal-source-format#4553</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4553/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/341">liferay-bpm-qa#341</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2170721757">[master] ci:test:sf - Luizcarlosqueiroz &gt; liferay-bpm-qa - PR#341 - 2023-01-23[12:13:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/16884/">publish-testray-report#16884</a><br/></div></div>

2023-01-23 20:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/4918/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4918/jenkins-report.html">here</a>.</b></p>

2023-01-23 20:42 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 20 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0593a802c3d5bf2004395c9769ed567330c444ba">0593a802c3d5bf2004395c9769ed567330c444ba</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/tree/LPS-163069-Automation">LPS-163069-Automation</a><br/>Branch GIT ID: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/commit/7cbbd16f4a84c04cabc579e70e97058e4e791bf2">7cbbd16f4a84c04cabc579e70e97058e4e791bf2</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/4918/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4918/jenkins-report.html">here</a>.</h5><div><p>POSHI Validation Failure<pre>     [exec] 1 errors in POSHI
     [exec] 
     [exec] Invalid macro command JSONObject#getObjectFilteredEntry at:
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-test/src/testFunctional/macros/ObjectAdmin.macro:642
     [exec]   635 |    macro assertObjectRelationshipNotPresent \{
     [exec]   636 |        AssertElementNotPresent(
     [exec]   637 |            key_label = "\$\{relationshipLabel\}",
     [exec]   638 |            locator1 = "ObjectAdmin#RELATIONSHIP_LABEL");
     [exec]   639 |    \}
     [exec]   640 |
     [exec]   641 |    macro assertObjectSearchEntry \{
     [exec] &gt; 642 |        var entryValue = JSONObject.getObjectFilteredEntry(
     [exec]   643 |            objectName = "\$\{objectName\}",
     [exec]   644 |            searchString = "\$\{searchString\}");
     [exec]   645 |
     [exec]   646 |        var entryFieldValue = JSONUtil.getWithJSONPath("\$\{entryValue\}", "\$..items..customObjectField");
     [exec]   647 |
     [exec]   648 |        TestUtils.assertEquals(
     [exec]   649 |            actual = "\$\{entryFieldValue\}",
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':validatePoshi'.
     [exec] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Get more help at https://help.gradle.org
     [exec] 
     [exec] BUILD FAILED</pre></p></div></details></html>

2023-01-23 20:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/4918/">test-portal-source-format#4918</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4918/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/341">liferay-bpm-qa#341</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2170723959">[master] ci:test:sf - Luizcarlosqueiroz &gt; liferay-bpm-qa - PR#341 - 2023-01-23[12:23:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/18866/">publish-testray-report#18866</a><br/></div></div>

2023-01-25 17:01 UTC, Luizcarlosqueiroz commented
ci:test:sf

2023-01-25 17:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3948/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3948/jenkins-report.html">here</a>.</b></p>

2023-01-25 17:05 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2fdc82473aefa0a68215f2a122e6e87758c4c3e8">2fdc82473aefa0a68215f2a122e6e87758c4c3e8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/tree/LPS-163069-Automation">LPS-163069-Automation</a><br/>Branch GIT ID: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/commit/a33dee4134d68cc203caca060a7a16f7cc2575a9">a33dee4134d68cc203caca060a7a16f7cc2575a9</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3948/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3948/jenkins-report.html">here</a>.</h5><div><p>POSHI Validation Failure<pre>     [exec] 1 errors in POSHI
     [exec] 
     [exec] Invalid macro command JSONObject#getObjectFilteredEntry at:
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-test/src/testFunctional/macros/ObjectAdmin.macro:642
     [exec]   635 |    macro assertObjectRelationshipNotPresent \{
     [exec]   636 |        AssertElementNotPresent(
     [exec]   637 |            key_label = "\$\{relationshipLabel\}",
     [exec]   638 |            locator1 = "ObjectAdmin#RELATIONSHIP_LABEL");
     [exec]   639 |    \}
     [exec]   640 |
     [exec]   641 |    macro assertObjectSearchEntry \{
     [exec] &gt; 642 |        var entryValue = JSONObject.getObjectFilteredEntry(
     [exec]   643 |            objectName = "\$\{objectName\}",
     [exec]   644 |            searchString = "\$\{searchString\}");
     [exec]   645 |
     [exec]   646 |        var entryFieldValue = JSONUtil.getWithJSONPath("\$\{entryValue\}", "\$..items..customObjectField");
     [exec]   647 |
     [exec]   648 |        TestUtils.assertEquals(
     [exec]   649 |            actual = "\$\{entryFieldValue\}",
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] &gt; Task :validatePoshi FAILED</pre></p></div></details></html>

2023-01-25 17:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3948/">test-portal-source-format#3948</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3948/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/341">liferay-bpm-qa#341</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2173326890">[master] ci:test:sf - Luizcarlosqueiroz &gt; liferay-bpm-qa - PR#341 - 2023-01-25[09:01:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/14733/">publish-testray-report#14733</a><br/></div></div>

2023-01-25 17:41 UTC, Luizcarlosqueiroz commented
ci:test:sf

2023-01-25 17:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3949/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3949/jenkins-report.html">here</a>.</b></p>

2023-01-25 17:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dc146fb13acb8f3ede19559bff019a203cd50635">dc146fb13acb8f3ede19559bff019a203cd50635</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/tree/LPS-163069-Automation">LPS-163069-Automation</a><br/>Branch GIT ID: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/commit/f47ba6968a5572030f3dc1ce06bb08d1526344e7">f47ba6968a5572030f3dc1ce06bb08d1526344e7</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3949/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3949/jenkins-report.html">here</a>.</h5></details></html>

2023-01-25 17:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3949/">test-portal-source-format#3949</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3949/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/341">liferay-bpm-qa#341</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2173370810">[master] ci:test:sf - Luizcarlosqueiroz &gt; liferay-bpm-qa - PR#341 - 2023-01-25[09:41:57]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/14736/">publish-testray-report#14736</a><br/></div></div>

2023-01-31 20:58 UTC, andreefarias requested changes
Hey @Luizcarlosqueiroz,

Occurs an error when run locally, fix it, please!

2023-01-31 21:15 UTC, andreefarias approved these changes

2023-02-01 06:57 UTC, timpak commented
Taking a look

2023-02-07 08:25 UTC, timpak requested changes
@Luizcarlosqueiroz can you also make the same changes as requested in https://github.com/liferay-bpm-qa/liferay-portal/pull/342#pullrequestreview-1286576388 here as well? There's also a small typo in the description.

The Given When Then is going to be slightly different:

Given: An custom object with a text field and three object entries
- Add custom object with field and publish
- Add object entries

When: An object entry is searched for using the API
- Hit the endpoint and store the result in a var

Then: one object entry is returned based on the search parameter

- Assertion only

2023-02-07 08:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/Object.testcase
> +	@description = "Verify it's possible to sort object entries by API"
Typo, I think you mean search here

2023-03-06 23:06 UTC, timpak commented
@Luizcarlosqueiroz can you take a look at the requested changes?

2023-03-13 14:08 UTC, Luizcarlosqueiroz commented
ci:test:sf

2023-03-13 14:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/1662/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/1662/jenkins-report.html">here</a>.</b></p>

2023-03-13 14:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8b6b423d4c583c4897fc1ac2d4c8de31eafe1cfb">8b6b423d4c583c4897fc1ac2d4c8de31eafe1cfb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/tree/LPS-163069-Automation">LPS-163069-Automation</a><br/>Branch GIT ID: <a href="https://github.com/Luizcarlosqueiroz/liferay-portal/commit/3980a9a22a92b3a4fadd59225d3350952a550876">3980a9a22a92b3a4fadd59225d3350952a550876</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/1662/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/1662/jenkins-report.html">here</a>.</h5></details></html>

2023-03-13 14:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/1662/">test-portal-source-format#1662</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/1662/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/341">liferay-bpm-qa#341</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2230248078">[master] ci:test:sf - Luizcarlosqueiroz &gt; liferay-bpm-qa - PR#341 - 2023-03-13[07:08:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/6848/">publish-testray-report#6848</a><br/></div></div>

2023-03-21 23:34 UTC, Luizcarlosqueiroz commented
ci:forward

2023-03-21 23:34 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2023-03-22 00:10 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-13.liferay.com/job/forward-pullrequest/421//consoleFull)

2023-03-22 00:10 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/132072
[Console](https://test-1-13.liferay.com/job/forward-pullrequest/421//consoleFull)

2023-03-22 00:10 UTC, closed without merging