LPS-161893 | master
liferay-bpm-qa/liferay-portal pull request #390
Opened 2023-02-02 08:45 UTC by liuxingye

https://issues.liferay.com/browse/LPS-161893

Hi, 

I wrote tests for export and import separately and moved the tests to ObjectExportImport test file.

Thanks.

2023-02-02 08:45 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-02-02 08:45 UTC, liuxingye commented
ci:test:sf

2023-02-02 08:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/5089/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5089/jenkins-report.html">here</a>.</b></p>

2023-02-02 08:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/faf682e989d8872bdea67d3b17c2d4318c888502">faf682e989d8872bdea67d3b17c2d4318c888502</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/liuxingye/liferay-portal/tree/master-lps-161893">master-lps-161893</a><br/>Branch GIT ID: <a href="https://github.com/liuxingye/liferay-portal/commit/4600afe2c3b4d1f7dd042d0a2d00abe4039349aa">4600afe2c3b4d1f7dd042d0a2d00abe4039349aa</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/5089/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5089/jenkins-report.html">here</a>.</h5></details></html>

2023-02-02 08:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/5089/">test-portal-source-format#5089</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5089/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/390">liferay-bpm-qa#390</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2183671534">[master] ci:test:sf - liuxingye &gt; liferay-bpm-qa - PR#390 - 2023-02-02[00:45:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/19538/">publish-testray-report#19538</a><br/></div></div>

2023-02-02 09:14 UTC, liuxingye commented
ci:test:sf

2023-02-02 09:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-23.liferay.com/job/test-portal-source-format/6508/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-source-format/builds/6508/jenkins-report.html">here</a>.</b></p>

2023-02-02 09:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/faf682e989d8872bdea67d3b17c2d4318c888502">faf682e989d8872bdea67d3b17c2d4318c888502</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/liuxingye/liferay-portal/tree/master-lps-161893">master-lps-161893</a><br/>Branch GIT ID: <a href="https://github.com/liuxingye/liferay-portal/commit/fbed65df8cb524d193b3b77cd8cd0c05635da985">fbed65df8cb524d193b3b77cd8cd0c05635da985</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-23.liferay.com/job/test-portal-source-format/6508/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-source-format/builds/6508/jenkins-report.html">here</a>.</h5></details></html>

2023-02-02 09:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-23.liferay.com/job/test-portal-source-format/6508/">test-portal-source-format#6508</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-source-format/builds/6508/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/390">liferay-bpm-qa#390</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2183681551">[master] ci:test:sf - liuxingye &gt; liferay-bpm-qa - PR#390 - 2023-02-02[01:14:41]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-23.liferay.com/job/publish-testray-report/1989/">publish-testray-report#1989</a><br/></div></div>

2023-02-07 08:48 UTC, timpak requested changes
Hey @liuxingye, great job with this test! Can you update the wording for the Given When Then and forward this?

2023-02-07 08:48 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectExportImport.testcase
> +		task ("Create Custom Object and Custom Relationship itself (via API)") {
Given: A custom object with a self-relationship

2023-02-07 08:48 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectExportImport.testcase
> +		task ("When go to Custom Object > Fields tab and add Custom Aggregation Field (via UI)") {
When: An Aggregation field is added to the custom object from the Fields tab

2023-02-07 08:48 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectExportImport.testcase
> +		task ("Then assert the object with aggregation field can be exported") {
Then: The custom object with a self-relationship and Aggregation field can be exported

2023-02-07 10:02 UTC, liuxingye commented
Thanks @timpak, please see https://github.com/liferay-bpm-qa/liferay-portal/pull/424

2023-02-07 10:02 UTC, closed without merging