LPS-176829
liferay-bpm-qa/liferay-portal pull request #523
Opened 2023-03-01 17:32 UTC by pedroamarall

2023-03-01 17:33 UTC, pedroamarall commented
ci:test:sf

2023-03-01 17:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/5029/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5029/jenkins-report.html">here</a>.</b></p>

2023-03-01 17:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5029/">test-portal-source-format#5029</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5029/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/523">liferay-bpm-qa#523</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2217705089">[master] ci:test:sf - pedroamarall &gt; liferay-bpm-qa - PR#523 - 2023-03-01[09:33:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/18994/">publish-testray-report#18994</a><br/></div></div>

2023-03-09 16:51 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +	@description = "LPS-176829 - Verify that Formula fields can't be required"
On @decription, use LPS from User Story: `LPS-164948`

2023-03-09 16:54 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +				pluralLabelName = "Custom Objects test");
In the `addObjectviaAPI`, we use the `Custom Object + LPS from the automation ticket`, this way we avoid errors in the CI due to duplicate objects.

Ex:
```
ObjectAdmin.addObjectViaAPI(
	labelName = "Custom Object 176829",
	objectName = "CustomObject176829",
	pluralLabelName = "Custom Objects 176829");
```

2023-03-09 16:54 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +			ObjectPortlet.selectSystemObject(label = "Custom Object test");
Change here too.

2023-03-09 17:15 UTC, andreefarias requested changes
Good job, @pedroamarall!

I requested only some changes. Fix it, please. Thanks!

2023-03-10 18:19 UTC, pedroamarall commented
ci:test:sf

2023-03-10 18:20 UTC, pedroamarall commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +		task ("Then:It's not possible to select mandatory option") {
Done @andreefarias, Thanks for your feedback

2023-03-10 18:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/4509/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4509/jenkins-report.html">here</a>.</b></p>

2023-03-10 18:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8b6b423d4c583c4897fc1ac2d4c8de31eafe1cfb">8b6b423d4c583c4897fc1ac2d4c8de31eafe1cfb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedroamarall/liferay-portal/tree/LPS-176829">LPS-176829</a><br/>Branch GIT ID: <a href="https://github.com/pedroamarall/liferay-portal/commit/efc60c56c47ae77a227aad417cfb40d59f08f328">efc60c56c47ae77a227aad417cfb40d59f08f328</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/4509/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4509/jenkins-report.html">here</a>.</h5></details></html>

2023-03-10 18:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/4509/">test-portal-source-format#4509</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4509/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/523">liferay-bpm-qa#523</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2228270392">[master] ci:test:sf - pedroamarall &gt; liferay-bpm-qa - PR#523 - 2023-03-10[10:20:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/16822/">publish-testray-report#16822</a><br/></div></div>

2023-03-22 22:09 UTC, andreefarias commented
Good job! Thanks for the collaboration @pedroamarall! 🎉 

I made some changes because it is necessary to assert the input as well, but I didn't write it in the steps, so I corrected it myself. Thanks!

2023-03-22 22:10 UTC, andreefarias commented
New PR [here](https://github.com/liferay-bpm-qa/liferay-portal/pull/617)

2023-03-22 22:10 UTC, andreefarias commented
ci:close

2023-03-22 22:10 UTC, closed without merging