LPS-176845
liferay-bpm-qa/liferay-portal pull request #538
Opened 2023-03-03 15:36 UTC by davisaints

2023-03-03 15:36 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-03-03 15:36 UTC, davisaints commented
ci:test:sf

2023-03-03 15:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/4112/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4112/jenkins-report.html">here</a>.</b></p>

2023-03-03 15:41 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6606d011fd06b8545ff74a964ba9433ef7170859">6606d011fd06b8545ff74a964ba9433ef7170859</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/davisaints/liferay-portal/tree/LPS-176845">LPS-176845</a><br/>Branch GIT ID: <a href="https://github.com/davisaints/liferay-portal/commit/9922d48cdd3295a7eeab64b65e78cb6669b2cd81">9922d48cdd3295a7eeab64b65e78cb6669b2cd81</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/4112/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4112/jenkins-report.html">here</a>.</h5></details></html>

2023-03-03 20:04 UTC, davisaints commented
ci:test:sf

2023-03-03 20:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/38/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/38/jenkins-report.html">here</a>.</b></p>

2023-03-03 20:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/67920bd52e844efe1f7e869ba5eb27c2000a8650">67920bd52e844efe1f7e869ba5eb27c2000a8650</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/davisaints/liferay-portal/tree/LPS-176845">LPS-176845</a><br/>Branch GIT ID: <a href="https://github.com/davisaints/liferay-portal/commit/70c2d38078a297f14ff633227c3a72ff3f8339a3">70c2d38078a297f14ff633227c3a72ff3f8339a3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/38/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/38/jenkins-report.html">here</a>.</h5></details></html>

2023-03-03 21:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/38/">test-portal-source-format#38</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/38/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/538">liferay-bpm-qa#538</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2220590414">[master] ci:test:sf - davisaints &gt; liferay-bpm-qa - PR#538 - 2023-03-03[12:04:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/65/">publish-testray-report#65</a><br/></div></div>

2023-03-07 21:20 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +				fieldType = "Integer");
It's possible to create it via API.

2023-03-07 21:24 UTC, andreefarias requested changes
Nice, it's good for me.

Only have some requests, fix it, please.

2023-03-07 21:26 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +		task ("Then: The Formula Builder is not searchable") {
`task ("Then: The Formula Field is not searchable") {`

2023-03-08 12:46 UTC, davisaints commented
ci:test:sf

2023-03-08 13:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-source-format/6775/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/6775/jenkins-report.html">here</a>.</b></p>

2023-03-08 13:02 UTC, closed without merging

2023-03-08 13:03 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7167fb45ee3ac3dc7e131e36c7a8d06997a43cf3">7167fb45ee3ac3dc7e131e36c7a8d06997a43cf3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/davisaints/liferay-portal/tree/LPS-176845">LPS-176845</a><br/>Branch GIT ID: <a href="https://github.com/davisaints/liferay-portal/commit/14d0b7cb0c7331fe41b9db7dad9a08115707bc60">14d0b7cb0c7331fe41b9db7dad9a08115707bc60</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-source-format/6775/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/6775/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./portal-impl/src/portal.properties expected:&lt;...ER1__NUMBER7__NUMBER[3__NUMBER5__NUMBER3__NUMBER7_
     [java]     #
     [java]     feature.flag.LPS-173537=false
     [java] 
     [java]     #
     [java]     # Env: LIFERAY_FEATURE_PERIOD_FLAG_PERIOD__UPPERCASEL__UPPERCASEP__UPPERCASES__MINUS__NUMBER1__NUMBER7__NUMBER]6__NUMBER0__NUMBER8_...&gt; but was:&lt;...ER1__NUMBER7__NUMBER[]6__NUMBER0__NUMBER8_...&gt;
     [java] 2: Truncated message :
     [java] ./modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase expected:&lt;...bject"
     [java]   @priority = [5
     [java]   test CanUpdateLayoutInSystemObject \{
     [java]     task ("Given: A custom object with a Layout") \{
     [java]       ObjectAdmin.addObjectViaAPI(
     [java]         labelName = "Custom Object 162190",
     [java]         objectName = "CustomObject162190",
     [java]         pluralLabelName = "Custom Objects 162190");
     [java] 
     [java]       ObjectAdmin.addObjectLayoutViaAPI(
     [java]         layoutName = "Layout",
     [java]         objectName = "CustomObject162190");
     [java] 
     [java]       ObjectAdmin.addObjectFieldViaAPI(
     [java]         fieldBusinessType = "Text",
     [java]         fieldLabelName = "Custom Field",
     [java]         fieldName = "customObjectField",
     [java]         fieldType = "String",
     [java]         isRequired = "false",
     [java]         objectName = "CustomObject162190");
     [java]     \}
     [java] 
     [java]     task ("When: Add field on created Layout and edit the name") \{
     [java]       ObjectAdmin.openObjectAdmin();
     [java] 
     [java]       ObjectPortlet.selectCustomObject(label = "Custom Object 162190");
     [java] 
     [java]       ObjectAdmin.goToLayoutsTab();
     [java] 
     [java]       ObjectAdmin.selectKebabMenuOption(kebabOption = "View");
     [java] 
     [java]       SelectFrame(locator1 = "IFrame#IFRAME");
     [java] 
     [java]       Click(locator1 = "ObjectAdmin#LAYOUT_LAYOUT_TAB");
     [java] 
     [java]       ObjectAdmin.addTabFieldsOnLayout(
     [java]         blockName = "Block Name",
     [java]         columnsNumber = 2,
     [java]         fieldLabelName = "Custom Field",
     [java]         tabName = "Field Tab");
     [java] 
     [java]       Click(locator1 = "ObjectAdmin#LAYOUT_INFO_TAB");
     [java] 
     [java]       Type(
     [java]         locator1 = "ObjectAdmin#LAYOUT_BASIC_INFO_NAME_FIELD",
     [java]         value1 = "Layout Updated");
     [java] </pre></details></html>

2023-03-08 13:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-source-format/6775/">test-portal-source-format#6775</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/6775/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/538">liferay-bpm-qa#538</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2224834435">[master] ci:test:sf - davisaints &gt; liferay-bpm-qa - PR#538 - 2023-03-08[04:59:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/2876/">publish-testray-report#2876</a><br/></div></div>