LPS-176837
liferay-bpm-qa/liferay-portal pull request #572
Opened 2023-03-15 13:45 UTC by davisaints

2023-03-15 13:45 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-03-15 13:46 UTC, davisaints commented
ci:test:sf

2023-03-15 13:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/4886/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4886/jenkins-report.html">here</a>.</b></p>

2023-03-21 22:48 UTC, Luizcarlosqueiroz requested changes
Hey @davisaints ! Could you take a look at the notes I made? Just minor changes.

2023-03-21 22:48 UTC, Luizcarlosqueiroz commented on modules/apps/object/object-test/src/testFunctional/paths/ObjectPortlet.path
> +		<td>//div[contains(@class,'ddm-field')]//input[contains(., readonly) and contains(@value, '${key_entry}')]</td>
When you want to check if a HTML element has a certain attribute, as in `contains(., readonly)`,  you can directly add `@readonly`. For exemple, [here](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uielements/TextInput.path#L505).

2023-03-21 22:48 UTC, Luizcarlosqueiroz commented on modules/apps/object/object-test/src/testFunctional/tests/CreateObject.testcase
> +			for (var accountNum : list "1,2") {
There's no need to add two accounts for this test, you call leave just one Account.

2023-03-21 22:48 UTC, Luizcarlosqueiroz commented on modules/apps/object/object-test/src/testFunctional/tests/CreateObject.testcase
> +			AssertClick(
Instead of an `AssertClick`, isn't better to use a `AssertVisible`?

2023-03-21 22:48 UTC, Luizcarlosqueiroz commented on modules/apps/object/object-test/src/testFunctional/tests/CreateObject.testcase
> +				value1 = ${key_entry});
Using the variable here might make the code less readable. Even though can look a little repetitive, using the "Account Test 1" in both makes it faster for the reader to understand what's being accomplished.

2023-03-23 18:33 UTC, davisaints commented
ci:test:sf

2023-03-23 18:36 UTC, davisaints commented
ci:stop

2023-03-23 18:37 UTC, davisaints commented
ci:test:sf

2023-03-23 19:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-source-format/6769/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/6769/jenkins-report.html">here</a>.</b></p>

2023-03-23 19:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3b85f2220d6e6d00209825b1d811cb032c090f1e">3b85f2220d6e6d00209825b1d811cb032c090f1e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/davisaints/liferay-portal/tree/LPS-176837">LPS-176837</a><br/>Branch GIT ID: <a href="https://github.com/davisaints/liferay-portal/commit/c5dfdb1a0c0687f297e94c4d4fd4a67f6d9facdf">c5dfdb1a0c0687f297e94c4d4fd4a67f6d9facdf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/6769/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/6769/jenkins-report.html">here</a>.</h5></details></html>

2023-03-23 19:47 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3b85f2220d6e6d00209825b1d811cb032c090f1e">3b85f2220d6e6d00209825b1d811cb032c090f1e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/davisaints/liferay-portal/tree/LPS-176837">LPS-176837</a><br/>Branch GIT ID: <a href="https://github.com/davisaints/liferay-portal/commit/c5dfdb1a0c0687f297e94c4d4fd4a67f6d9facdf">c5dfdb1a0c0687f297e94c4d4fd4a67f6d9facdf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/5907/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/5907/jenkins-report.html">here</a>.</h5></details></html>

2023-03-23 22:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/5907/">test-portal-source-format#5907</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/5907/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/572">liferay-bpm-qa#572</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2243360806">[master] ci:test:sf - davisaints &gt; liferay-bpm-qa - PR#572 - 2023-03-23[12:43:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/3371/">publish-testray-report#3371</a><br/></div></div>

2023-03-23 22:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-source-format/6769/">test-portal-source-format#6769</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/6769/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/572">liferay-bpm-qa#572</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2243362595">[master] ci:test:sf - davisaints &gt; liferay-bpm-qa - PR#572 - 2023-03-23[12:41:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/3606/">publish-testray-report#3606</a><br/></div></div>

2023-04-05 07:35 UTC, timpak approved these changes

2023-04-05 07:35 UTC, timpak commented
ci:forward

2023-04-05 07:36 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-04-05 07:36 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2023-04-05 07:37 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-28.liferay.com/job/forward-pullrequest/628//consoleFull)

2023-04-05 07:37 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/132878
[Console](https://test-1-28.liferay.com/job/forward-pullrequest/628//consoleFull)

2023-04-05 07:37 UTC, closed without merging