LPS-176828
liferay-bpm-qa/liferay-portal pull request #586
Opened 2023-03-17 14:26 UTC by GABRIELCMSANTOS

2023-03-17 14:26 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-03-17 14:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/5794/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5794/jenkins-report.html">here</a>.</b></p>

2023-03-17 14:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/5794/">test-portal-source-format#5794</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5794/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/586">liferay-bpm-qa#586</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2235491564">[master] ci:test:sf - GABRIELCMSANTOS &gt; liferay-bpm-qa - PR#586 - 2023-03-17[07:29:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/22161/">publish-testray-report#22161</a><br/></div></div>

2023-03-21 20:06 UTC, Luizcarlosqueiroz requested changes
Hey @GABRIELCMSANTOS ! Could you check the comments I've made?

2023-04-05 08:32 UTC, timpak requested changes
@GABRIELCMSANTOS please see my comments for some minor changes. You can forward this once you take care of them. Please follow up with @Luizcarlosqueiroz if you aren't sure or have questions.

2023-04-05 08:32 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/macros/ObjectAdmin.macro
> +
We don't need to create a macro for this since it's only one function. You can just call the function directly in the test case

2023-04-05 08:32 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +				formulaFieldOption = "Decimal");
This should be part of the given.

2023-04-05 08:32 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +		task ("Given: an Object") {
Move the steps to add the formula field to this task. Change the wording to:
`Given a custom object with a formula field`

2023-04-05 08:32 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +		task ("When: managing a Formula Field") {
When using the Formula Builder for the formula field

2023-04-05 08:32 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +		task ("Then: Formula Builder has principal math operations") {
Then the Formula Builder contains the principal math operations

2023-04-12 07:02 UTC, timpak commented
@GABRIELCMSANTOS can you please take a look at the requested changes when you have a chance?
cc: @Luizcarlosqueiroz

2023-04-13 06:38 UTC, timpak requested changes
@GABRIELCMSANTOS can you fix the commit message for https://github.com/liferay-bpm-qa/liferay-portal/pull/586/commits/93ae026a2f6a4a5be7fc9c1d5b3d85e9374c76b7? Since you're adding a test, your commit message should reflect this.

2023-04-26 08:10 UTC, timpak commented
Hey @GABRIELCMSANTOS, can you update the commit message to better reflect what it does? @Luizcarlosqueiroz can you help @GABRIELCMSANTOS address this so we can move forward with this PR?

2023-05-04 21:31 UTC, Luizcarlosqueiroz approved these changes
LGMT! :tada:

2023-05-04 21:31 UTC, Luizcarlosqueiroz commented
ci:forward

2023-05-04 21:31 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-05-04 21:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-source-format/6911/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/6911/jenkins-report.html">here</a>.</b></p>

2023-05-04 21:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/16a196570228b5d85decf60ed49bb3a25bf366b3">16a196570228b5d85decf60ed49bb3a25bf366b3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/GABRIELCMSANTOS/liferay-portal/tree/LPS-176828">LPS-176828</a><br/>Branch GIT ID: <a href="https://github.com/GABRIELCMSANTOS/liferay-portal/commit/c77aec62ecaaa9db3a4f5193feb4cdcf7e6ef326">c77aec62ecaaa9db3a4f5193feb4cdcf7e6ef326</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-source-format/6911/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/6911/jenkins-report.html">here</a>.</h5></details></html>

2023-05-04 21:38 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-21.liferay.com/job/test-portal-source-format/6911//consoleFull)

2023-05-04 21:38 UTC, closed without merging

2023-05-04 21:38 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/134362
[Console](https://test-1-21.liferay.com/job/test-portal-source-format/6911//consoleFull)

2023-05-04 21:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-source-format/6911/">test-portal-source-format#6911</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/6911/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/586">liferay-bpm-qa#586</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2290687550">[master] ci:test:sf - GABRIELCMSANTOS &gt; liferay-bpm-qa - PR#586 - 2023-05-04[14:32:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/3049/">publish-testray-report#3049</a><br/></div></div>

2023-05-04 22:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8021/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8021/jenkins-report.html">here</a>.</b></p>

2023-05-04 22:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8021/">test-portal-acceptance-pullrequest(master)#8021</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8021/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/586">liferay-bpm-qa#586</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2290738644">[master] ci:test:relevant - GABRIELCMSANTOS &gt; liferay-bpm-qa - PR#586 - 2023-05-04[15:34:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/18157/">publish-testray-report#18157</a><br/></div></div>