LPS-161904
liferay-bpm-qa/liferay-portal pull request #68
Opened 2022-10-19 20:47 UTC by evanilson-santana

2022-10-19 20:47 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-10-19 20:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3407/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3407/jenkins-report.html">here</a>.</b></p>

2022-10-19 20:52 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/588fab011753e36d56630ca5a21e797f2d727fa5">588fab011753e36d56630ca5a21e797f2d727fa5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LPS-161904">LPS-161904</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/3a392d799f042d82281651ea4521d4cd1f6b49af">3a392d799f042d82281651ea4521d4cd1f6b49af</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3407/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3407/jenkins-report.html">here</a>.</h5></details></html>

2022-10-19 20:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3407/">test-portal-source-format#3407</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3407/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/68">liferay-bpm-qa#68</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2010847961">[master] ci:test:sf - evanilson-santana &gt; liferay-bpm-qa - PR#68 - 2022-10-19[13:48:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/12601/">publish-testray-report#12601</a><br/></div></div>

2022-10-25 16:59 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				locator1 = "ObjectPortlet#ENTRY_VALUE");
There is a macro that asserts this step, search for `viewEntry`

2022-10-25 17:00 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				locator1 = "ObjectPortlet#ENTRY_VALUE");
Same thing here.

2022-10-25 17:06 UTC, andreefarias commented
Hey @evanilson-santana,

The code looks good to me. There are some small details just to improve.

2022-10-25 17:10 UTC, andreefarias requested changes
See my requests, please.

2022-10-25 17:10 UTC, andreefarias requested changes
.

2022-10-27 09:31 UTC, timpak requested changes
Hey @evanilson-santana good job with these tests. Please see my comments below. You can forward these to BChan once you're done.

2022-10-27 09:31 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		}
We should only have one given here. We can combine this into one task: `Given a Grooy Script and an object with two text fields are created`

2022-10-27 09:31 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		task ("When an action is created using script groovy") {
Change this to `When an action is created using Groovy Script`

2022-10-27 09:31 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		task ("Then the action of adding an entry is created") {
Change this to `Then the object entry is created when the condition is met`

2022-10-27 09:31 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		task ("Given an object and a field created by API") {
`Given an object and a field are created`

2022-10-27 09:31 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				whenAction = "On After Add");
Turn this into a task: `When the action is added`

2022-10-27 09:31 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		}
Combine this into one task: `Then the object entry is created when the condition is met`

2022-10-27 09:31 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		}
We can combine this into one task: `Given a Grooy Script, an object with two text fields, an object entry, and an Action using Groovy Script are created`

2022-10-27 09:31 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				whenAction = "On After Update");
Turn this into a task: `When the Action is edited`

2022-10-27 09:31 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		}
Create a new task: `Then the object entry name is updated when the condition is met`

2022-10-27 09:31 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		}
We don't need to test the Action here since we're asserting that the Action can be triggered in other tests.

2022-10-27 09:31 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		}
Combine this into one task `Given an object with a field and an Action with an Expression are created

2022-10-27 09:31 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +			ObjectAdmin.disableCondition();
Turn this into a task: `When the Expression in the Action is disabled`

2022-10-27 09:31 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		}
Turn this into a task: `Then the Action will resolve when the condition is met`

2022-10-28 08:03 UTC, timpak requested changes
Hey @evanilson-santana I updated the tasks to use multiple Givens. Please let me know if you need me to clarify anything. Once you make your changes, you can forward this to BChan.

2022-10-28 08:03 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		task ("Given an object, two fields and an entry is created") {
And given an object with two fields and an object entry are created

2022-10-28 08:03 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		}
And given an action using a Groovy Script is created

2022-10-28 08:03 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		task ("Given an object and a field is created") {
Given an object with a field is created

2022-10-28 08:03 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		task ("Given an action is defined") {
Given an Action with an expression is created

2022-11-04 14:17 UTC, evanilson-santana commented
ci:forward

2022-11-04 14:17 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-11-04 14:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/1768/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/1768/jenkins-report.html">here</a>.</b></p>

2022-11-04 14:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/86666c74f6d2b29f3a31bbf25523e944375556eb">86666c74f6d2b29f3a31bbf25523e944375556eb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LPS-161904">LPS-161904</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/4f0c4d95dccd436094326d68fa23e77f58c1019a">4f0c4d95dccd436094326d68fa23e77f58c1019a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-source-format/1768/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/1768/jenkins-report.html">here</a>.</h5></details></html>

2022-11-04 14:21 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-35.liferay.com/job/test-portal-source-format/1768//consoleFull)

2022-11-04 14:22 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/125796
[Console](https://test-1-35.liferay.com/job/test-portal-source-format/1768//consoleFull)

2022-11-04 14:22 UTC, closed without merging

2022-11-04 14:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/1768/">test-portal-source-format#1768</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/1768/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/68">liferay-bpm-qa#68</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2033632158">[master] ci:test:sf - evanilson-santana &gt; liferay-bpm-qa - PR#68 - 2022-11-04[07:18:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/6877/">publish-testray-report#6877</a><br/></div></div>

2022-11-04 14:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5265/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5265/jenkins-report.html">here</a>.</b></p>

2022-11-04 14:29 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5265//consoleFull)

2022-11-04 14:29 UTC, liferay-continuous-integration commented
Closed pull request will not be forwarded.

2022-11-04 14:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5265/">test-portal-acceptance-pullrequest(master)#5265</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5265/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/68">liferay-bpm-qa#68</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2033633639">[master] ci:test:relevant - evanilson-santana &gt; liferay-bpm-qa - PR#68 - 2022-11-04[07:26:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/13063/">publish-testray-report#13063</a><br/></div></div>