LPS-180195 | Add test CanTriggerAddActionWithSystemObjectToItselfWhenAdd
liferay-bpm-qa/liferay-portal pull request #692
Opened 2023-04-12 09:20 UTC by bronsonsoda

https://issues.liferay.com/browse/LPS-180195

2023-04-12 09:20 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-04-12 16:36 UTC, nikki-pru commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		task ("Given a Account object and given an action to create a new Account entry after adding an Account entry") {
Task block description does not match what's inside the block.

2023-04-12 16:38 UTC, nikki-pru commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +			Type(
Macros please for type and clicks. Having the actions here does not describe what's going on and it makes it harder to understand the flow of the test. Other team members or test analysts will not be able to readily decode what's going on here. 

Also, macros for reusability.

2023-04-12 16:38 UTC, nikki-pru commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +			ObjectAdmin.addObjectSingleFieldEntryViaAPI(
This is the When block

2023-04-12 16:38 UTC, nikki-pru commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +			ObjectAdmin.goToActionsTab();
This is the then block for final assertion

2023-04-12 16:39 UTC, nikki-pru commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +	@description = "LPS-180195 - Verify on the Account object if it's possible to trigger an action with ADD when ADD an account"
Use the story ticket for the description because we are testing the Story, not the testing task. LPS-173537

2023-04-20 18:24 UTC, timpak commented
@andreefarias can you take a look at this since we updated the test and steps?

2023-04-20 19:42 UTC, andreefarias commented
Nice, thanks for your job @bronsonsoda!

I'll cherry-pick this PR with some others to fix conflicts. The small fixes I'll fix.

cc: @timpak

2023-04-26 20:51 UTC, andreefarias commented
I'll close this PR. This testcase is related to this PR: #753 which was cherry-picked with others and resolved the conflict.

Thanks for your collaboration.

2023-05-08 14:43 UTC, andreefarias commented
Hey @bronsonsoda , I reopened this PR to fix some things. I'll review and request some changes.

2023-05-08 14:49 UTC, andreefarias commented
I'll review based on it: #753

2023-05-08 15:40 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +	@description = "LPS-173537 - Verify on the Account object if it's possible to trigger an action with ADD when ADD an account"
Update the description to: `LPS-173537 - Verify creating an Account entry triggers an action to add a second Account entry`

2023-05-08 17:08 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		task ("Given a Account object and given an action to add a new Account entry after creating an Account entry") {
task ("Given an Account object")

2023-05-08 17:21 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				inputSecondValue = "customField");
These steps on Custom Object are not needed.

`Given 1:` Go to Account Object
`Given 2:` Add action on Account
`When:` Create Account
`Then:` Assert new Account created

2023-05-08 17:23 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				status = "Success");
These steps are not needed. Assert on Account admin the new Account created

2023-05-08 17:23 UTC, andreefarias commented
ci:test:sf

2023-05-08 17:38 UTC, andreefarias requested changes
Hey @bronsonsoda,

I requested some changes, could review it, please? I added the test steps to make it easier to understand.

2023-05-10 05:47 UTC, bronsonsoda commented
@andreefarias changes made

2023-05-10 05:50 UTC, bronsonsoda commented
ci:test:sf

2023-05-10 05:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/5149/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5149/jenkins-report.html">here</a>.</b></p>

2023-05-10 05:54 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4586debf7fb573475819e6df6ede2ee31efefd16">4586debf7fb573475819e6df6ede2ee31efefd16</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/bronsonsoda/liferay-portal/tree/LPS-180195">LPS-180195</a><br/>Branch GIT ID: <a href="https://github.com/bronsonsoda/liferay-portal/commit/670f328efa599c509e3ffe368ef2abee9ca16ecc">670f328efa599c509e3ffe368ef2abee9ca16ecc</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5149/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5149/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Truncated message :
     [java] ./modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase expected:&lt;...description = "LPS-1[73537 - Verify creating an Account entry triggers an action to add a second Account entry"
     [java]   @priority = 5
     [java]   test CanAddAccountEntryAfterCreatingAccountEntry \{
     [java]     property portal.acceptance = "true";
     [java] 
     [java]     task ("Given an Account object") \{
     [java]       ObjectAdmin.addObjectViaAPI(
     [java]         labelName = "Custom Object 180195",
     [java]         objectName = "CustomObject180195",
     [java]         pluralLabelName = "Custom Objects 180195");
     [java]     \}
     [java] 
     [java]     task ("And given an action to add a new Account entry after creating an Account entry") \{
     [java]       ObjectAdmin.addObjectFieldViaAPI(
     [java]         fieldBusinessType = "Integer",
     [java]         fieldLabelName = "Custom Field",
     [java]         fieldName = "customField",
     [java]         fieldType = "Integer",
     [java]         isRequired = "false",
     [java]         objectName = "CustomObject180195");
     [java] 
     [java]       ObjectAdmin.publishObjectViaAPI(objectName = "CustomObject180195");
     [java] 
     [java]       ObjectAdmin.openObjectAdmin();
     [java] 
     [java]       ObjectPortlet.selectCustomObject(label = "Custom Object 180195");
     [java] 
     [java]       ObjectAdmin.goToActionsTab();
     [java] 
     [java]       ObjectAdmin.addObjectActionViaUI(
     [java]         actionLabel = "Custom Action",
     [java]         actionName = "CustomAction",
     [java]         active = "true",
     [java]         inputMethod = "true",
     [java]         inputValue = "Account Name,Person",
     [java]         objectLabel = "Account",
     [java]         thenAction = "Add an Object Entry",
     [java]         whenAction = "On After Add");
     [java]     \}
     [java] 
     [java]     task ("When the user creates an Account entry") \{
     [java]       ObjectAdmin.addObjectSingleFieldEntryViaAPI(
     [java]         fieldName = "customField",
     [java]         objectName = "CustomObject180195",
     [java]         value = 1);
     [java]     \}
     [java] 
     [java]     task ("Then the action is triggered and a second Account entry is added") \{
     [java]       Account.openAccountsAdmin();
     [java] 
     [java]       LexiconEntry.viewEntryName(rowEntry = "Account Name");
     [java]     \}
     [java]   \}
     [java] </pre></details></html>

2023-05-10 05:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5149/">test-portal-source-format#5149</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5149/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/692">liferay-bpm-qa#692</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2299601763">[master] ci:test:sf - bronsonsoda &gt; liferay-bpm-qa - PR#692 - 2023-05-09[22:50:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/19247/">publish-testray-report#19247</a><br/></div></div>

2023-05-10 07:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/5150/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5150/jenkins-report.html">here</a>.</b></p>

2023-05-10 07:08 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4586debf7fb573475819e6df6ede2ee31efefd16">4586debf7fb573475819e6df6ede2ee31efefd16</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/bronsonsoda/liferay-portal/tree/LPS-180195">LPS-180195</a><br/>Branch GIT ID: <a href="https://github.com/bronsonsoda/liferay-portal/commit/8632843aa5fcda7df0120e2e517d7c7eefea0b4e">8632843aa5fcda7df0120e2e517d7c7eefea0b4e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5150/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5150/jenkins-report.html">here</a>.</h5></details></html>

2023-05-10 07:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5150/">test-portal-source-format#5150</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5150/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/692">liferay-bpm-qa#692</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2299637201">[master] ci:test:sf - bronsonsoda &gt; liferay-bpm-qa - PR#692 - 2023-05-10[00:02:40]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/19249/">publish-testray-report#19249</a><br/></div></div>

2023-05-10 13:12 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +			ObjectPortlet.selectCustomObject(label = "Custom Object 180195");
These steps are related to Custom Object, so aren't necessary. Delete, please.

The goal is to create an Action in Account to Account.

2023-05-10 13:23 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				value = 1);
So, now do you need to create a new Account (you can use via API):

```
JSONAccountEntry.addAccountEntry(
	accountEntryName = "Business Account",
	accountEntryType = "Business");

Account.openAccountsAdmin();
```

2023-05-10 13:34 UTC, andreefarias requested changes
Hey @bronsonsoda,

I saw that you use Custom Object to test it, but not needed, because the main goal is to use the System Object Account and test your action. I requested more some changes, could verify it, please? Let me know about any questions.

2023-05-10 15:29 UTC, bronsonsoda commented
@andreefarias fixed

2023-05-10 17:40 UTC, andreefarias approved these changes
Nice! Thanks for the updates and help! 

LGTM! 🎉

2023-05-12 21:46 UTC, epark18 commented
ci:forward

2023-05-12 21:46 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-05-12 21:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/11419/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11419/jenkins-report.html">here</a>.</b></p>

2023-05-12 21:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/6695/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6695/jenkins-report.html">here</a>.</b></p>

2023-05-12 21:49 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fe3c34314ebba0343bb825d9ca88b405c2a1f96d">fe3c34314ebba0343bb825d9ca88b405c2a1f96d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/bronsonsoda/liferay-portal/tree/LPS-180195">LPS-180195</a><br/>Branch GIT ID: <a href="https://github.com/bronsonsoda/liferay-portal/commit/b0f830ec2360b7d83396be00915e1e2016bdb481">b0f830ec2360b7d83396be00915e1e2016bdb481</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/6695/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6695/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase expected:&lt;...n.openObjectAdmin();[]
     [java] 
     [java]       ObjectPortlet.s...&gt; but was:&lt;...n.openObjectAdmin();[ ]
     [java] 
     [java]       ObjectPortlet.s...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:466)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
[stopwatch] [run.batch.test.action: 1:20.263 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:597: Java returned: 1
      [get] Getting: http://test-1-37/job/test-portal-source-format/6695//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230512144922700.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230512144922700.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null690451772.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null623979960
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 168ms
[junitreport] Deleting: /tmp/null623979960
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 05-12-2023 14:49:24:797 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</pre></details></html>

2023-05-12 22:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/6695/">test-portal-source-format#6695</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6695/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/692">liferay-bpm-qa#692</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2302715988">[master] ci:test:sf - bronsonsoda &gt; liferay-bpm-qa - PR#692 - 2023-05-12[14:46:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/25287/">publish-testray-report#25287</a><br/></div></div>

2023-05-12 22:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/11419/">test-portal-acceptance-pullrequest(master)#11419</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11419/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/692">liferay-bpm-qa#692</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2302716750">[master] ci:test:relevant - bronsonsoda &gt; liferay-bpm-qa - PR#692 - 2023-05-12[14:46:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/25288/">publish-testray-report#25288</a><br/></div></div>

2023-05-15 22:14 UTC, epark18 commented
@bronsonsoda Can you fix your SF error and forward

2023-05-25 07:21 UTC, timpak requested changes

2023-05-25 07:21 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +			ObjectAdmin.openObjectAdmin();
Looks like there's an unnecessary whitespace at the end of the line @bronsonsoda

2023-05-30 17:03 UTC, bronsonsoda commented
ci:forward

2023-05-30 17:03 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-05-30 17:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/4578/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4578/jenkins-report.html">here</a>.</b></p>

2023-05-30 17:08 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/125a112452daa3d47caa5acc0e87d767f30ab4dc">125a112452daa3d47caa5acc0e87d767f30ab4dc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/bronsonsoda/liferay-portal/tree/LPS-180195">LPS-180195</a><br/>Branch GIT ID: <a href="https://github.com/bronsonsoda/liferay-portal/commit/91994ba95a51d90d0cb2e9a8ab2bca04e8a48315">91994ba95a51d90d0cb2e9a8ab2bca04e8a48315</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/4578/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4578/jenkins-report.html">here</a>.</h5></details></html>

2023-05-30 17:08 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-29.liferay.com/job/test-portal-source-format/4578//consoleFull)

2023-05-30 17:09 UTC, closed without merging

2023-05-30 17:09 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/135599
[Console](https://test-1-29.liferay.com/job/test-portal-source-format/4578//consoleFull)

2023-05-30 17:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/4578/">test-portal-source-format#4578</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4578/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/692">liferay-bpm-qa#692</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2324671216">[master] ci:test:sf - bronsonsoda &gt; liferay-bpm-qa - PR#692 - 2023-05-30[10:03:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/16922/">publish-testray-report#16922</a><br/></div></div>

2023-05-30 18:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/7322/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7322/jenkins-report.html">here</a>.</b></p>

2023-05-30 18:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/7322/">test-portal-acceptance-pullrequest(master)#7322</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7322/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/692">liferay-bpm-qa#692</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2324738074">[master] ci:test:relevant - bronsonsoda &gt; liferay-bpm-qa - PR#692 - 2023-05-30[11:24:38]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/16926/">publish-testray-report#16926</a><br/></div></div>