LPS-180082, LPS-180083, LPS-180087 | Test Automation | Master
liferay-bpm-qa/liferay-portal pull request #722
Opened 2023-04-18 16:07 UTC by JerryAdrianoo

**Tickets Jira:**

> [LPS-180082](https://issues.liferay.com/browse/LPS-180082)
> [LPS-180083](https://issues.liferay.com/browse/LPS-180083)
> [LPS-180087](https://issues.liferay.com/browse/LPS-180087)

2023-04-18 16:07 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-04-18 16:10 UTC, JerryAdrianoo commented
ci:test:sf

2023-04-18 16:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/290/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/290/jenkins-report.html">here</a>.</b></p>

2023-04-18 16:14 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ca6f69f0ebf1252262b61d765543fc818a6c1f67">ca6f69f0ebf1252262b61d765543fc818a6c1f67</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JerryAdrianoo/liferay-portal/tree/LPS-180082">LPS-180082</a><br/>Branch GIT ID: <a href="https://github.com/JerryAdrianoo/liferay-portal/commit/ed4cbff575ff2cc0699a45f4895fa587e04194a4">ed4cbff575ff2cc0699a45f4895fa587e04194a4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/290/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/290/jenkins-report.html">here</a>.</h5></details></html>

2023-04-18 16:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/290/">test-portal-source-format#290</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/290/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/722">liferay-bpm-qa#722</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2273279075">[master] ci:test:sf - JerryAdrianoo &gt; liferay-bpm-qa - PR#722 - 2023-04-18[09:10:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/1010/">publish-testray-report#1010</a><br/></div></div>

2023-04-18 18:18 UTC, JerryAdrianoo commented
ci:test:sf

2023-04-18 18:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/889/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/889/jenkins-report.html">here</a>.</b></p>

2023-04-18 18:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ca6f69f0ebf1252262b61d765543fc818a6c1f67">ca6f69f0ebf1252262b61d765543fc818a6c1f67</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JerryAdrianoo/liferay-portal/tree/LPS-180082">LPS-180082</a><br/>Branch GIT ID: <a href="https://github.com/JerryAdrianoo/liferay-portal/commit/db96514956f8d63052fdaa8f654c355768ff50e2">db96514956f8d63052fdaa8f654c355768ff50e2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/889/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/889/jenkins-report.html">here</a>.</h5></details></html>

2023-04-18 18:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/889/">test-portal-source-format#889</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/889/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/722">liferay-bpm-qa#722</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2273430612">[master] ci:test:sf - JerryAdrianoo &gt; liferay-bpm-qa - PR#722 - 2023-04-18[11:19:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/2934/">publish-testray-report#2934</a><br/></div></div>

2023-04-20 19:42 UTC, andreefarias commented
Nice, thanks for your job @JerryAdrianoo!

I'll cherry-pick this PR with some others to fix conflicts. The small fixes I'll fix.

2023-04-26 20:51 UTC, andreefarias commented
I'll close this PR. This testcase is related to this PR: #753 which was cherry-picked with others and resolved the conflict.

Thanks for your collaboration.

2023-05-08 14:42 UTC, andreefarias commented
Hey @JerryAdrianoo, I reopened this PR to fix some things. I'll review and request some changes.

2023-05-10 18:52 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +			ObjectAdmin.editEntryName(newEntryValue = "Entry Test Edited");
Replace these steps to:

`ObjectPortlet.updateEntry`

2023-05-10 18:53 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +			ObjectPortlet.viewEntry(entry = "Entry Test Edited");
It's not necessary to assert the entry is updated. We have a test that covers this step. Delete, please.

2023-05-10 18:55 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				value1 = "Entry Test");
It's not necessary to assert the entry is updated. We have a test that covers this step. Delete, please.

2023-05-10 18:55 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				value1 = "Entry Test");
It's not necessary to assert the entry is updated. We have a test that covers this step. Delete, please.

2023-05-10 19:14 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		task ("And given an action to create a new Account entry after adding an entry on Custom Object") {
`task ("And given an action to add an Account entry after creating a custom object entry")`

2023-05-10 19:16 UTC, andreefarias requested changes
Hey @JerryAdrianoo, thanks for testcases. I requested some changes, could you look, please? 

Fix the rebase of the branch and verify if is necessary to include this path and macros.

2023-05-12 13:04 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +	@description = "LPS-180070 - Verify creating a Commerce Product entry triggers an action to add a user"
@description = "[LPS-173537](https://issues.liferay.com/browse/LPS-173537) - Verify creating a custom object entry triggers an action to add an Account entry"

2023-05-12 13:20 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> -	test CanAddUserAfterCreatingCommerceProductEntry {
Hey @JerryAdrianoo, don't overwrite this testcase, verify it, please.

2023-05-12 13:23 UTC, andreefarias requested changes
Hey @JerryAdrianoo I requested you to change the description of a testcase and confirm that the existing testcase is not overwritten. Check when possible, please.

2023-05-12 16:25 UTC, andreefarias approved these changes
Nice @JerryAdrianoo!

LGTM! 🎉

2023-05-25 07:31 UTC, timpak requested changes
Hey @JerryAdrianoo can you take a look at my comments below? There's a merge conflict as well, can you remove 4d62dead0bc725c157bcf12a1b84585e210d60eb and fe3c34314ebba0343bb825d9ca88b405c2a1f96d from your branch?

2023-05-25 07:31 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		}
We don't need to create a separate step for this. We can just include this while adding the action.

2023-05-25 07:31 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		task ("Given a Custom Object and an object entry") {
`custom object`

We don't need to capitalize `Custom Object` because it isn't a proper noun.

2023-05-29 05:04 UTC, timpak commented
See https://github.com/liferay-bpm-qa/liferay-portal/pull/864

2023-05-29 05:04 UTC, closed without merging