LPS-182078
liferay-bpm-qa/liferay-portal pull request #724
Opened 2023-04-18 18:48 UTC by davisaints

2023-04-18 18:48 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-04-18 18:52 UTC, davisaints commented
ci:test:sf

2023-04-18 18:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ca6f69f0ebf1252262b61d765543fc818a6c1f67">ca6f69f0ebf1252262b61d765543fc818a6c1f67</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/davisaints/liferay-portal/tree/LPS-182078">LPS-182078</a><br/>Branch GIT ID: <a href="https://github.com/davisaints/liferay-portal/commit/c97afa8556faa4f114897409a08bb19e1cb57ed9">c97afa8556faa4f114897409a08bb19e1cb57ed9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/6039/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/6039/jenkins-report.html">here</a>.</h5></details></html>

2023-04-18 18:57 UTC, andreefarias commented
This testcase is blocked by the bug: [LPS-181920](https://issues.liferay.com/browse/LPS-181920).

Waiting for merge to review it.

2023-04-18 19:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/6039/">test-portal-source-format#6039</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/6039/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/724">liferay-bpm-qa#724</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2273450549">[master] ci:test:sf - davisaints &gt; liferay-bpm-qa - PR#724 - 2023-04-18[11:52:22]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/21936/">publish-testray-report#21936</a><br/></div></div>

2023-04-19 17:30 UTC, andreefarias approved these changes
Nice @davisaints, good job!

LGTM! 🎉

2023-04-19 17:31 UTC, andreefarias commented
ci:test:sf

2023-04-19 17:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/2609/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2609/jenkins-report.html">here</a>.</b></p>

2023-04-19 17:35 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f37b1ce60e91915c4b3b60abcd88c47acac7c9cb">f37b1ce60e91915c4b3b60abcd88c47acac7c9cb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/davisaints/liferay-portal/tree/LPS-182078">LPS-182078</a><br/>Branch GIT ID: <a href="https://github.com/davisaints/liferay-portal/commit/3b83b7b60ddeda7bbf61dbe9b5444e440678952b">3b83b7b60ddeda7bbf61dbe9b5444e440678952b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/2609/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2609/jenkins-report.html">here</a>.</h5></details></html>

2023-04-19 17:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/2609/">test-portal-source-format#2609</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2609/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/724">liferay-bpm-qa#724</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2274759937">[master] ci:test:sf - davisaints &gt; liferay-bpm-qa - PR#724 - 2023-04-19[10:31:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/9468/">publish-testray-report#9468</a><br/></div></div>

2023-05-02 09:59 UTC, timpak requested changes
@davisaints good job with this test! Can you take a look at my comments below? You can forward this once you make the changes.

2023-05-02 09:59 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +		task ("And given a custom object entry") {
And given an object entry with an attachment

2023-05-02 09:59 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +		task ("When going to Global Site and into the Documents and Media") {
When the user navigates to Documents and Media in the global site

2023-05-02 09:59 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFields.testcase
> +		task ("Then assert that exist the attachment field from a custom object") {
Then a folder is seen that contains the attachment from the object entry

2023-05-02 13:13 UTC, davisaints commented
ci:test:sf

2023-05-02 13:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/118b9dca04af1162e6ab784dc33fc6b62c8f7e80">118b9dca04af1162e6ab784dc33fc6b62c8f7e80</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/davisaints/liferay-portal/tree/LPS-182078">LPS-182078</a><br/>Branch GIT ID: <a href="https://github.com/davisaints/liferay-portal/commit/f417fef2f9b7ebb028919394d11fba5942c5e3ef">f417fef2f9b7ebb028919394d11fba5942c5e3ef</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/4826/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4826/jenkins-report.html">here</a>.</h5></details></html>

2023-05-02 13:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/4826/">test-portal-source-format#4826</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4826/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/724">liferay-bpm-qa#724</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2286841876">[master] ci:test:sf - davisaints &gt; liferay-bpm-qa - PR#724 - 2023-05-02[06:13:29]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/18053/">publish-testray-report#18053</a><br/></div></div>

2023-05-02 13:21 UTC, davisaints commented
ci:forward

2023-05-02 13:21 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-05-02 13:21 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2023-05-02 13:22 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-33.liferay.com/job/forward-pullrequest/346//consoleFull)

2023-05-02 13:35 UTC, davisaints commented
ci:reopen

2023-05-02 13:42 UTC, davisaints commented
ci:forward

2023-05-02 13:42 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2023-05-02 13:43 UTC, closed without merging

2023-05-02 13:43 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/134221
[Console](https://test-1-40.liferay.com/job/forward-pullrequest/234//consoleFull)

2023-05-02 13:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1087/">test-portal-source-format#1087</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1087/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/724">liferay-bpm-qa#724</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2286855004">[master] ci:test:sf - davisaints &gt; liferay-bpm-qa - PR#724 - 2023-05-02[06:38:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/3558/">publish-testray-report#3558</a><br/></div></div>