LPS-179579
liferay-bpm-qa/liferay-portal pull request #731
Opened 2023-04-19 16:47 UTC by mateussandes23

2023-04-19 16:47 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-04-19 16:50 UTC, mateussandes23 commented
ci:test:sf

2023-04-19 16:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/2605/">test-portal-source-format#2605</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2605/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/731">liferay-bpm-qa#731</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2274701794">[master] ci:test:sf - mateussandes23 &gt; liferay-bpm-qa - PR#731 - 2023-04-19[09:50:41]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/9459/">publish-testray-report#9459</a><br/></div></div>

2023-04-19 17:02 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase
> +			PortletEntry.save();
This `PortletEntry.save();` is not necessary, because the macro `addSingleFieldEntryViaUI` already made it.

2023-04-19 17:05 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase
> +		}
Assert the error message given to `invalidFields` when adding `Entry Decline`

2023-04-19 17:06 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase
> +		}
The error message: `"This entry is not possible."`

2023-04-19 17:07 UTC, andreefarias requested changes
Hey @mateussandes23,

Thanks for the fix. I requested only some changes to better the code, review it, please. Thanks!

2023-04-24 06:58 UTC, timpak commented
@mateussandes23 do you need to make additional changes or can I review this?

2023-04-25 12:59 UTC, mateussandes23 commented
Hey @timpak its everything okay, you can review now. Sorry for the delay on answer.

2023-04-25 17:58 UTC, andreefarias commented
Hey @mateussandes23,

the file changes are fine for me, however, the commits are confusing. Could you rename it in a unique commit related to the fix?

2023-04-26 08:48 UTC, timpak commented
This test looks like it's doing the exact same thing as `ObjectCustomValidation.CanAddEntryWhenPassesForAllValidations`. Can we do the following?
-  Update `CanAddEntryWhenPassesForAllValidations` to be a positive assertion and only add an entry that passes validation
- - Update the test name to `CanAddEntry`. Since it's within the ObjectCustomValidation file, the assumption is that it's a validation test.
- Update `CanUserAddValidationsGroovy` to be a negative assertion and only attempt to add an entry that won't pass validation
- - Update the test name to `CanPreventEntryCreationViaGroovy` 

For you commit message, can you use present tense? Also, we want to use descriptive commit messages so that we understand what the commit is doing. Your message indicates that you're fixing something but it doesn't tell me what's going on. This isn't a hard rule but it's good practice to help reviewers and and other people understand what your changes do and why you made those changes.

2023-05-03 20:30 UTC, andreefarias approved these changes

2023-05-03 20:31 UTC, andreefarias commented
Thanks for the updates @mateussandes23!

LGTM! 🎉

2023-05-08 07:38 UTC, timpak approved these changes
Hi @mateussandes23 two reminders:

1. Please use present tense for your commit messages from now on. I'll forward this for now but I'll reject commits in the future if they don't use present tense. @andreefarias, please enforce this during your reviews. I can explain this more during our meeting on Tuesday if needed.
2. Use multiple commits if you need to modify multiple tests. If you're making the same change to each test, it's fine to use one commit but when you need to make various changes to the tests, it's better to split to use multiple commits. This makes it easier to review and it makes it easier to understand what the changes are doing when viewing the commit history. @andreefarias please enforce this as well during your reviews.

2023-05-08 07:38 UTC, timpak commented
ci:forward

2023-05-08 07:38 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-05-08 07:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ac2b995b2e12cbd85683c513548e954786d2cbaf">ac2b995b2e12cbd85683c513548e954786d2cbaf</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-179579">LPS-179579</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/6bf870a3ee03fdcf4547525eb7f8e19c781de880">6bf870a3ee03fdcf4547525eb7f8e19c781de880</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/4877/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4877/jenkins-report.html">here</a>.</h5></details></html>

2023-05-08 07:42 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-27.liferay.com/job/test-portal-source-format/4877//consoleFull)

2023-05-08 07:42 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/134474
[Console](https://test-1-27.liferay.com/job/test-portal-source-format/4877//consoleFull)

2023-05-08 07:42 UTC, closed without merging

2023-05-08 07:43 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8057//consoleFull)

2023-05-08 07:43 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/134475
[Console](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8057//consoleFull)

2023-05-08 07:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/4877/">test-portal-source-format#4877</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4877/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/731">liferay-bpm-qa#731</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2297241150">[master] ci:test:sf - mateussandes23 &gt; liferay-bpm-qa - PR#731 - 2023-05-08[00:38:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/18232/">publish-testray-report#18232</a><br/></div></div>

2023-05-08 07:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8057/">test-portal-acceptance-pullrequest(master)#8057</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8057/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/731">liferay-bpm-qa#731</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2297241332">[master] ci:test:relevant - mateussandes23 &gt; liferay-bpm-qa - PR#731 - 2023-05-08[00:38:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/18233/">publish-testray-report#18233</a><br/></div></div>