LPS-178248
liferay-bpm-qa/liferay-portal pull request #748
Opened 2023-04-25 20:11 UTC by JerryAdrianoo

2023-04-25 20:11 UTC, JerryAdrianoo commented
ci:test:sf

2023-04-25 20:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/378/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/378/jenkins-report.html">here</a>.</b></p>

2023-04-25 20:22 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 11 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/693d69ff522cb867204acbb1758c449390338efc">693d69ff522cb867204acbb1758c449390338efc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JerryAdrianoo/liferay-portal/tree/LPS-178248">LPS-178248</a><br/>Branch GIT ID: <a href="https://github.com/JerryAdrianoo/liferay-portal/commit/d8591e9dd26ef6154f8ecc0877bd1af6a6adeedb">d8591e9dd26ef6154f8ecc0877bd1af6a6adeedb</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/378/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/378/jenkins-report.html">here</a>.</h5></details></html>

2023-04-25 20:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/378/">test-portal-source-format#378</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/378/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/748">liferay-bpm-qa#748</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2280472337">[master] ci:test:sf - JerryAdrianoo &gt; liferay-bpm-qa - PR#748 - 2023-04-25[13:11:54]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/1308/">publish-testray-report#1308</a><br/></div></div>

2023-04-25 21:50 UTC, Luizcarlosqueiroz requested changes
Hey @JerryAdrianoo !  Could you check my comments? Thanks!!

2023-04-25 21:50 UTC, Luizcarlosqueiroz commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uisections/PagesConfiguration.path
>  	<td>CONTENT_CHOOSE_CONTENT_CONTENT_CHECKBOX</td>
This path is used by other macros. Did you check if these changes won't change the behavior for other tests?

2023-04-25 21:50 UTC, Luizcarlosqueiroz commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uisections/PagesConfiguration.path
> +	<td>//span[contains(.,'Private Pages')]//input[contains(@type,'checkbox')] | //span[contains(.,'Staging Test Page')]//input[contains(@type,'checkbox')]</td>
This path is supposed to be only for private pages. I was unable to find where is being used, but in theory, we should use another macro for a Staging page.

2023-04-27 13:55 UTC, Luizcarlosqueiroz approved these changes
LGTM! :tada:

2023-04-28 16:27 UTC, patriciajeanperez commented
ci:forward

2023-04-28 16:27 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-04-28 16:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/df115f11c69bb28a7915435bb7ff559d233a5369">df115f11c69bb28a7915435bb7ff559d233a5369</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JerryAdrianoo/liferay-portal/tree/LPS-178248">LPS-178248</a><br/>Branch GIT ID: <a href="https://github.com/JerryAdrianoo/liferay-portal/commit/583cd441d6fd30b7ab82cb5cfa5e0eca92dab28a">583cd441d6fd30b7ab82cb5cfa5e0eca92dab28a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/426/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/426/jenkins-report.html">here</a>.</h5></details></html>

2023-04-28 16:32 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/426//consoleFull)

2023-04-28 16:33 UTC, closed without merging

2023-04-28 16:33 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/134152
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/426//consoleFull)

2023-04-28 16:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/426/">test-portal-source-format#426</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/426/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/748">liferay-bpm-qa#748</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2284725643">[master] ci:test:sf - JerryAdrianoo &gt; liferay-bpm-qa - PR#748 - 2023-04-28[09:28:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/1457/">publish-testray-report#1457</a><br/></div></div>

2023-04-28 18:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/746/">test-portal-acceptance-pullrequest(master)#746</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/746/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/748">liferay-bpm-qa#748</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2284748679">[master] ci:test:relevant - JerryAdrianoo &gt; liferay-bpm-qa - PR#748 - 2023-04-28[10:59:51]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/1460/">publish-testray-report#1460</a><br/></div></div>