LPS-178371 - Fix ObjectCustomLayouts#CanSelectExistingEntriesOnRelationshipTab
liferay-bpm-qa/liferay-portal pull request #751
Opened 2023-04-26 16:50 UTC by thaiscabrals

2023-04-26 16:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/397/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/397/jenkins-report.html">here</a>.</b></p>

2023-04-26 16:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6e2d1d7fd25f7fa834e3875941ab5e6941ffa501">6e2d1d7fd25f7fa834e3875941ab5e6941ffa501</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaiscabrals/liferay-portal/tree/LPS-178371">LPS-178371</a><br/>Branch GIT ID: <a href="https://github.com/thaiscabrals/liferay-portal/commit/d15d62ba4a84e7c41b2dded0e45cd2f94fc334d3">d15d62ba4a84e7c41b2dded0e45cd2f94fc334d3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/397/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/397/jenkins-report.html">here</a>.</h5></details></html>

2023-04-26 16:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/397/">test-portal-source-format#397</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/397/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/751">liferay-bpm-qa#751</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2281469692">[master] ci:test:sf - thaiscabrals &gt; liferay-bpm-qa - PR#751 - 2023-04-26[09:52:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/1364/">publish-testray-report#1364</a><br/></div></div>

2023-04-26 17:33 UTC, patriciajeanperez commented
Hello Thais! I was looking at the screenshot of the failing tests and it looks like the element is there so we wouldn't really need to wait for an element to be present. Have we tried to see if the locator needs updating? Please don't forget to upload an html file of the passing test too when submitting a test fix. Thank you!

cc @timpak

2023-04-26 19:07 UTC, thaiscabrals commented
ci:test:sf

2023-04-26 19:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 13 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6e2d1d7fd25f7fa834e3875941ab5e6941ffa501">6e2d1d7fd25f7fa834e3875941ab5e6941ffa501</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaiscabrals/liferay-portal/tree/LPS-178371">LPS-178371</a><br/>Branch GIT ID: <a href="https://github.com/thaiscabrals/liferay-portal/commit/115fcfad1b1a7f474227e7c11a1324446bb49e2b">115fcfad1b1a7f474227e7c11a1324446bb49e2b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/4431/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4431/jenkins-report.html">here</a>.</h5></details></html>

2023-04-26 19:22 UTC, thaiscabrals commented
Hey @patriciajeanperez 
Thanks for your help. I have modified and added the file to the ticket.

2023-04-26 19:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/4431/">test-portal-source-format#4431</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4431/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/751">liferay-bpm-qa#751</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2281628928">[master] ci:test:sf - thaiscabrals &gt; liferay-bpm-qa - PR#751 - 2023-04-26[12:07:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/15866/">publish-testray-report#15866</a><br/></div></div>

2023-04-26 19:32 UTC, patriciajeanperez requested changes
Hi Thais! Please take note that there are two tests (`LocalFile.ObjectCustomLayouts#CanAddEntryOnRelationshipTabForMtoM
` and `LocalFile.ObjectCustomLayouts#CanSelectExistingEntriesOnRelationshipTab`) that are failing from this error. Please make sure both tests are considered when submitting a fix.

One thing to note though is that there is another test in that testcase that uses the same locator and it is consistently passing. Maybe we can compare that test to the other two that are failing to see what we are missing?

2023-04-26 19:32 UTC, patriciajeanperez commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomLayouts.testcase
> +			ClickNoError(
@thaiscabrals The failure happens when asserting `ObjectAdmin#VIEW_OBJECT_FIELD_LABEL`, so I am not sure if this will fix the test.

2023-04-27 11:33 UTC, closed without merging

2023-04-27 14:28 UTC, thaiscabrals commented
The new changes are being made in this [commit](https://github.com/liferay-bpm-qa/liferay-portal/pull/756).