LPS-178371 - Fix ObjectCustomLayouts#CanAddEntryOnRelationshipTabForMtoM
liferay-bpm-qa/liferay-portal pull request #756
Opened 2023-04-27 13:59 UTC by thaiscabrals

2023-04-27 13:59 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-04-27 14:04 UTC, thaiscabrals commented
ci:test:sf

2023-04-27 14:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/6413/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6413/jenkins-report.html">here</a>.</b></p>

2023-04-27 14:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ae34144d5834a359ee012551b024ed55ddb3c33e">ae34144d5834a359ee012551b024ed55ddb3c33e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaiscabrals/liferay-portal/tree/FixObjects">FixObjects</a><br/>Branch GIT ID: <a href="https://github.com/thaiscabrals/liferay-portal/commit/bc0337a5bcf44f3514bc5638eeb657b148d75838">bc0337a5bcf44f3514bc5638eeb657b148d75838</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/6413/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6413/jenkins-report.html">here</a>.</h5></details></html>

2023-04-28 15:50 UTC, patriciajeanperez requested changes
Hi @thaiscabrals! Thank you for the fix. I left a comment but please let me know what you think. Thank you!

For next time, the index.html file is what you would want to upload in JIRA so we can view the passing test/s. It should be under the folder of the test in the `test-results` folder. Just make sure you also rename the file to the test especially if there are more than one test you are uploading so it is easier to distinguish. Thank you!

2023-04-28 15:50 UTC, patriciajeanperez commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomLayouts.testcase
> +			CreateObject.addRelationshipAndSelectEntry(titleFieldName = "Entry Test C");
@thaiscabrals hmm I don't think we need to repeat the same steps to make sure `Entry Test C` is there. Would just selecting the frame and then waiting for the page to load work just like in `CreateObject.addRelationshipAndSelectEntry`?

2023-05-02 20:34 UTC, thaiscabrals commented
ci:test:sf

2023-05-02 20:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/6491/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6491/jenkins-report.html">here</a>.</b></p>

2023-05-02 20:39 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e57cae7bea4b38dd0f319ac072df90a1c1976df2">e57cae7bea4b38dd0f319ac072df90a1c1976df2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaiscabrals/liferay-portal/tree/FixObjects">FixObjects</a><br/>Branch GIT ID: <a href="https://github.com/thaiscabrals/liferay-portal/commit/50fe61429e7e0f5f9b7a067eb4b0b5411108c1fa">50fe61429e7e0f5f9b7a067eb4b0b5411108c1fa</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/6491/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6491/jenkins-report.html">here</a>.</h5></details></html>

2023-05-02 20:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/6491/">test-portal-source-format#6491</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6491/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/756">liferay-bpm-qa#756</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2287296751">[master] ci:test:sf - thaiscabrals &gt; liferay-bpm-qa - PR#756 - 2023-05-02[13:34:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/24595/">publish-testray-report#24595</a><br/></div></div>

2023-05-03 18:17 UTC, patriciajeanperez commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomLayouts.testcase
> +			WaitForPageLoad();
I think this should be after you click on Entry Test C? @thaiscabrals

2023-05-03 21:20 UTC, thaiscabrals commented
ci:test:sf

2023-05-03 21:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/6452/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6452/jenkins-report.html">here</a>.</b></p>

2023-05-03 21:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9fc6e620978d62ff73bbe859cd5c620ae7297170">9fc6e620978d62ff73bbe859cd5c620ae7297170</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaiscabrals/liferay-portal/tree/FixObjects">FixObjects</a><br/>Branch GIT ID: <a href="https://github.com/thaiscabrals/liferay-portal/commit/4d739fab420606567f16b96d82781b9086351f19">4d739fab420606567f16b96d82781b9086351f19</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6452/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6452/jenkins-report.html">here</a>.</h5></details></html>

2023-05-03 21:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6452/">test-portal-source-format#6452</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6452/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/756">liferay-bpm-qa#756</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2288673987">[master] ci:test:sf - thaiscabrals &gt; liferay-bpm-qa - PR#756 - 2023-05-03[14:21:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/3973/">publish-testray-report#3973</a><br/></div></div>

2023-05-15 12:41 UTC, closed without merging