LPS-183650
liferay-bpm-qa/liferay-portal pull request #780
Opened 2023-05-05 11:54 UTC by victorhcunha

2023-05-05 11:54 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-05-05 15:21 UTC, victorhcunha commented
ci:test:sf

2023-05-05 15:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/6550/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6550/jenkins-report.html">here</a>.</b></p>

2023-05-05 15:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/6550/">test-portal-source-format#6550</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6550/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/780">liferay-bpm-qa#780</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2291796795">[master] ci:test:sf - victorhcunha &gt; liferay-bpm-qa - PR#780 - 2023-05-05[08:21:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/24795/">publish-testray-report#24795</a><br/></div></div>

2023-05-05 17:41 UTC, andreefarias commented
Good job @victorhcunha! 

One question, there is some testcase that executes the navigate via the portlet menu? It's important to cover this part in at least one testcase.

2023-05-05 17:53 UTC, victorhcunha commented
Hi @andreefarias !
There are many tests that keep using portlet step

2023-05-05 18:05 UTC, andreefarias commented
Nice list @victorhcunha , thanks! Could replace all? Except for this testcase: `ObjectNotifications#CanCreateEmailTemplate`. This way the main test to create a template will follow the steps as the user. Does that make sense?

2023-05-05 19:10 UTC, victorhcunha commented
Hi @andreefarias !
Make sense to me, now only two tests are still using the portlet menu to make those steps, CanSendEmailViaActionAdd (to Queue) and CanCreateEmailTemplate (to Template).

2023-05-05 19:23 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +			Notifications.notificationQueueAdmin();
Use the: `Notifications.notificationTemplateAdmin();`

2023-05-05 19:24 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectNotifications.testcase
> -				pluralLabelName = "Custom Objects 161928");
Don't replace the `addObjectViaAPI` to `Notifications.notificationTemplateAdmin();`

2023-05-05 19:44 UTC, andreefarias approved these changes
Nice @victorhcunha!
LGTM! 🎉

2023-05-08 08:07 UTC, timpak requested changes
Really great job with this refactor, @victorhcunha!! One small request: can you rename the macros to:
`goToNotificationQueueAdmin` 
`goToNotificationTemplateAdmin` 

The current macro names don't clearly explain what they're doing. Don't forget to sort the macros once you rename them!

2023-05-08 19:07 UTC, victorhcunha commented
@timpak 
This macros are renamed by #764

2023-05-09 08:55 UTC, timpak commented
@victorhcunha, you need to either include the macro rename in your changes. For example:
- `LPS-183650 Rename the notification navigation macros`
   - Use this commit to rename the macros
- `LPS-183650 Replace old navigation steps
   - Use this commit to apply the navigation macros to the tests

Instead of having someone else fix your changes like [this](https://github.com/liferay-bpm-qa/liferay-portal/pull/764/commits/7b7941291e5e2feafbd05a9c07eb12a3b11b5131), it's better to do it right the first time.

2023-05-26 17:28 UTC, victorhcunha commented
ci:reopen

2023-05-29 05:10 UTC, timpak approved these changes
Great job re-organizing the commits @victorhcunha and @JerryAdrianoo!!

In the future, you can just use `Wordsmith` for commits like e30896c4df077224a2ef11312b9f99599ce76648. See https://github.com/liferay-bpm-qa/liferay-portal/pull/864/commits/985d542a9cfff734d1e17430a7333809cc686c4a for an example.

2023-05-29 05:10 UTC, timpak commented
ci:forward

2023-05-29 05:10 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-05-29 05:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/2728/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2728/jenkins-report.html">here</a>.</b></p>

2023-05-29 05:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/5715/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5715/jenkins-report.html">here</a>.</b></p>

2023-05-29 05:14 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b2329712c814f5ff77c0bd1b019d699237dfa5e1">b2329712c814f5ff77c0bd1b019d699237dfa5e1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/victorhcunha/liferay-portal/tree/LPS-183650">LPS-183650</a><br/>Branch GIT ID: <a href="https://github.com/victorhcunha/liferay-portal/commit/74473f4be1bbe19ef057274461b043e87569abc1">74473f4be1bbe19ef057274461b043e87569abc1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5715/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5715/jenkins-report.html">here</a>.</h5></details></html>

2023-05-29 05:14 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-26.liferay.com/job/test-portal-source-format/5715//consoleFull)

2023-05-29 05:15 UTC, closed without merging

2023-05-29 05:15 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/135500
[Console](https://test-1-26.liferay.com/job/test-portal-source-format/5715//consoleFull)

2023-05-29 05:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5715/">test-portal-source-format#5715</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5715/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/780">liferay-bpm-qa#780</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2322990475">[master] ci:test:sf - victorhcunha &gt; liferay-bpm-qa - PR#780 - 2023-05-28[22:10:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/21914/">publish-testray-report#21914</a><br/></div></div>

2023-05-29 05:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/2728/">test-portal-acceptance-pullrequest(master)#2728</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2728/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/780">liferay-bpm-qa#780</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2322990491">[master] ci:test:relevant - victorhcunha &gt; liferay-bpm-qa - PR#780 - 2023-05-28[22:10:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/5075/">publish-testray-report#5075</a><br/></div></div>