LPS-181943
liferay-bpm-qa/liferay-portal pull request #795
Opened 2023-05-08 14:36 UTC by victorhcunha

2023-05-08 14:36 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-05-08 14:47 UTC, victorhcunha commented
ci:test:sf

2023-05-08 14:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/4886/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4886/jenkins-report.html">here</a>.</b></p>

2023-05-08 14:52 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/576a6c09f5f21bd0fb6d556c08bf678c242f34f6">576a6c09f5f21bd0fb6d556c08bf678c242f34f6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/victorhcunha/liferay-portal/tree/LPS-181943">LPS-181943</a><br/>Branch GIT ID: <a href="https://github.com/victorhcunha/liferay-portal/commit/a37e06c9bd7d174cb27446da5296d404a7b95d24">a37e06c9bd7d174cb27446da5296d404a7b95d24</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/4886/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4886/jenkins-report.html">here</a>.</h5></details></html>

2023-05-08 14:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/4886/">test-portal-source-format#4886</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4886/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/795">liferay-bpm-qa#795</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2297491530">[master] ci:test:sf - victorhcunha &gt; liferay-bpm-qa - PR#795 - 2023-05-08[07:48:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/18247/">publish-testray-report#18247</a><br/></div></div>

2023-05-10 19:21 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				portlet = "Products");
You could use: `CommerceProducts.openProductsAdmin();`

2023-05-10 19:23 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				productType = "Simple");
Verify if is works with: `CommerceJSONProductsAPI._addCommerceProduct`

There are simple examples with it, we don't have to access and add the product via UI.

2023-05-10 19:25 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				portlet = "Products");
Access via URL: `CommerceProducts.openProductsAdmin();`

2023-05-10 19:30 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		task ("Given a minium site and Commerce Product") {
`task ("Given a minium site and Commerce Product object")`

2023-05-10 19:36 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				productType = "Simple");
Verify if it works with: `CommerceJSONProductsAPI._addCommerceProduct`

2023-05-10 19:37 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +				portlet = "Products");
Access via URL: `CommerceProducts.openProductsAdmin();`

2023-05-10 22:00 UTC, victorhcunha commented
ci:test:sf

2023-05-10 22:03 UTC, victorhcunha commented
Hi @andreefarias !
All the changes have been made. Can you see it again?

2023-05-10 22:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/1202/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1202/jenkins-report.html">here</a>.</b></p>

2023-05-10 22:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 18 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/73ab9bf82e0d38f99fabc6a51416cfe7bc2f07d1">73ab9bf82e0d38f99fabc6a51416cfe7bc2f07d1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/victorhcunha/liferay-portal/tree/LPS-181943">LPS-181943</a><br/>Branch GIT ID: <a href="https://github.com/victorhcunha/liferay-portal/commit/ebc7b6f12103a01745c8cb6506f7d852e7115242">ebc7b6f12103a01745c8cb6506f7d852e7115242</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1202/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1202/jenkins-report.html">here</a>.</h5></details></html>

2023-05-10 22:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1202/">test-portal-source-format#1202</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1202/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/795">liferay-bpm-qa#795</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2300576291">[master] ci:test:sf - victorhcunha &gt; liferay-bpm-qa - PR#795 - 2023-05-10[15:01:04]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/3972/">publish-testray-report#3972</a><br/></div></div>

2023-05-12 12:46 UTC, andreefarias approved these changes
Nice @victorhcunha!

LGTM! 🎉

2023-05-25 09:14 UTC, timpak requested changes
@victorhcunha just some minor wording updates, you can forward this after you update the strings.

2023-05-25 09:14 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		task ("Given a minium site and Commerce Product object") {
Given a Minium site and a Commerce Product

2023-05-25 09:14 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		task ("Given a minium site and Commerce Product object") {
Given a Minium site and a Commerce Product

2023-05-25 09:14 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		task ("Then the action is triggered and the Commerce Product entry changed is updated") {
Then the action is triggered and the updated Commerce Product entry is updated again

2023-05-25 19:48 UTC, victorhcunha commented
ci:test:sf

2023-05-25 19:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/4372/">test-portal-source-format#4372</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4372/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/795">liferay-bpm-qa#795</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2320162918">[master] ci:test:sf - victorhcunha &gt; liferay-bpm-qa - PR#795 - 2023-05-25[12:50:22]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/3622/">publish-testray-report#3622</a><br/></div></div>

2023-05-25 20:00 UTC, victorhcunha commented
ci:foward

2023-05-25 20:02 UTC, victorhcunha commented
ci:forward

2023-05-25 20:02 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-05-25 20:02 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2023-05-25 20:06 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-5.liferay.com/job/forward-pullrequest/262//consoleFull)

2023-05-25 20:07 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/135408
[Console](https://test-1-5.liferay.com/job/forward-pullrequest/262//consoleFull)

2023-05-29 12:05 UTC, victorhcunha commented
ci:reopen

2023-05-29 14:10 UTC, victorhcunha commented
ci:forward

2023-05-29 14:10 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-05-29 14:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/9469/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9469/jenkins-report.html">here</a>.</b></p>

2023-05-29 14:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/4476/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4476/jenkins-report.html">here</a>.</b></p>

2023-05-29 14:14 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6632af54295fb2d4589e6366ee10b000c2f8568a">6632af54295fb2d4589e6366ee10b000c2f8568a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/victorhcunha/liferay-portal/tree/LPS-181943">LPS-181943</a><br/>Branch GIT ID: <a href="https://github.com/victorhcunha/liferay-portal/commit/c8f04b21aa3c015f534aff76843b0fd4e41e8f43">c8f04b21aa3c015f534aff76843b0fd4e41e8f43</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/4476/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4476/jenkins-report.html">here</a>.</h5></details></html>

2023-05-29 14:15 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-30.liferay.com/job/test-portal-source-format/4476//consoleFull)

2023-05-29 14:15 UTC, closed without merging

2023-05-29 14:15 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/135530
[Console](https://test-1-30.liferay.com/job/test-portal-source-format/4476//consoleFull)

2023-05-29 14:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/9469/">test-portal-acceptance-pullrequest(master)#9469</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9469/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/795">liferay-bpm-qa#795</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2323352698">[master] ci:test:relevant - victorhcunha &gt; liferay-bpm-qa - PR#795 - 2023-05-29[07:10:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/21934/">publish-testray-report#21934</a><br/></div></div>

2023-05-29 14:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/4476/">test-portal-source-format#4476</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4476/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/795">liferay-bpm-qa#795</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2323352709">[master] ci:test:sf - victorhcunha &gt; liferay-bpm-qa - PR#795 - 2023-05-29[07:11:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/16787/">publish-testray-report#16787</a><br/></div></div>