LPS-186246
liferay-bpm-qa/liferay-portal pull request #874
Opened 2023-06-05 18:28 UTC by Natanaelbenvindo

2023-06-05 18:32 UTC, Natanaelbenvindo commented
ci:test:sf

2023-06-05 20:37 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +				fieldType = "Date and Time");
```
ObjectAdmin.addObjectFieldViaUI(
	fieldLabel = "Custom Date Time",
	fieldTimeStorage = "fieldTimeStorage = "Use Input as Entered",
	fieldType = "Date and Time");
```

2023-06-05 20:38 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +				fieldType = "Date and Time");
Use Input as Entered here:

```
ObjectAdmin.addObjectFieldViaUI(
	fieldLabel = "Custom Date Time",
	fieldTimeStorage = "fieldTimeStorage = "Use Input as Entered",
	fieldType = "Date and Time");
```

2023-06-05 20:40 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +				userEmailAddress = "userea@liferay.com");
This step isn't necessary.

2023-06-05 20:51 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +				value = "2023-06-01T12:00:00.000Z");
Could use a date with AM?

2023-06-05 20:55 UTC, andreefarias commented
ci:test:sf

2023-06-05 21:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-source-format/6975/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/6975/jenkins-report.html">here</a>.</b></p>

2023-06-05 21:47 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 51 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6186bdf6e205c1d0cfafead8bacd76b8153e0ff5">6186bdf6e205c1d0cfafead8bacd76b8153e0ff5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Natanaelbenvindo/liferay-portal/tree/LPS-186246">LPS-186246</a><br/>Branch GIT ID: <a href="https://github.com/Natanaelbenvindo/liferay-portal/commit/1702991177e8bdef86aeceaec9af0524dbaa20ea">1702991177e8bdef86aeceaec9af0524dbaa20ea</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-source-format/6975/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/6975/jenkins-report.html">here</a>.</h5></details></html>

2023-06-05 21:52 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-source-format/6975/">test-portal-source-format#6975</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/6975/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/874">liferay-bpm-qa#874</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2340714055">[master] ci:test:sf - Natanaelbenvindo &gt; liferay-bpm-qa - PR#874 - 2023-06-05[13:56:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/3136/">publish-testray-report#3136</a><br/></div></div>

2023-06-06 13:41 UTC, Natanaelbenvindo commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +				userEmailAddress = "userea@liferay.com");
ok

2023-06-06 14:45 UTC, andreefarias approved these changes
Nice! Good job @Natanaelbenvindo!

LGTM! 🎉

2023-06-07 06:25 UTC, timpak requested changes
@Natanaelbenvindo please see my feedback below. Some notes:
- Do not deviate from the steps on the spreadsheet after they've been reviewed. If you need to modify the steps, I need to review them again. Pay careful attention to the wording and follow them exactly. Adding typos and grammar mistakes creates more work for the both of us.
- Do not modify the wording of the description and steps at all. If they need to be modified, it must pass through me first. 
- Please familiarize yourself with the user flow for objects. We should be adding the field before publishing the object. We shouldn't be able to publish the object definition without adding a field.

Modifying the steps and wording without clearing it with me generates a lot of extra work on my end during PR review. In the future, please do not do this without talking to me first.

@andreefarias please flag issues like during the initial review and push the PR back to the author to follow the original test design. We shouldn't be deviating from it unless we have a very good reason.

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +		task ("Given a custom object with a date and time field as input as entered") {
Given a custom object with a date and time field and the time storage set to user input

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +			ObjectAdmin.publishObjectViaAPI(objectName = "CustomObject186246");
We shouldn't be publishing the object definition until we're done setting it up

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +				fieldType = "Date and Time");
Can we add the field using our API instead?

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +		task ("Then the date and time is seen on the table entries") {
Then the date and time seen on the table

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +	@description = "LPS-143068  - Verify if is possible to see DateTime with differents Time Zone"
Verify the date and time are adjusted to the user's time zone

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +		task ("Given a custom object with a date and time field as UTC") {
Given a custom object with a date and time field as UTC and an object entry

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +			ObjectAdmin.publishObjectViaAPI(objectName = "CustomObject186248");
We shouldn't be publishing here

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +				fieldType = "Date and Time");
Same thing as the previous test, can we add the field using the API instead?

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +			PortletEntry.save();
I'm not sure what this is accomplishing in terms of the test, can you explain why were adding these steps?

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +		}
This should be part of the previous given

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +		task ("When access the user") {
This isn't following the original test design

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +			PortletEntry.save();
Do we need to do this as `usersn` or can we set the the time zone for the user as `Test Test`?

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +		task ("Then assert that time zone is correct") {
Then the time is adjusted to the user's time zone

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +	@description = "LPS-143068 - Verify if is possible to edit DateTime on entries from Custom Object"
Verify a custom object entry with a date and time field can be updated

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +		task ("Given a custom object with a date and time field as UTC") {
Given a custom object with a date and time field and an object entry

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +			ObjectAdmin.publishObjectViaAPI(objectName = "CustomObject186247");
Same thing here, we shouldn't be publishing the object until we're done setting it up

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +				fieldType = "Date and Time");
Same thing here, can we use our API instead?

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +		task ("When the user update the entry") {
`When the user updates the entry`

Please pay careful attention to the wording on the spreadsheet

2023-06-07 06:25 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +		task ("Then the date and time is updated on the table entries") {
Then the date and time are updated on the table

2023-06-07 19:51 UTC, andreefarias commented
Hey @timpak,

@Natanaelbenvindo wrote the description/task looking at the ticket but forgot to update the ticket after you updated the sheets.

My review was based on the ticket description/task. Some technical errors were not caught by me, it won't happen again. Thanks for bringing it to me.

2023-06-09 07:19 UTC, timpak commented
@Natanaelbenvindo if this is ready for review, please remove the `Author Action Required` label, remove yourself as an assignee. and assign the PR to me. Thanks!

2023-06-14 23:57 UTC, timpak requested changes
Hey @Natanaelbenvindo please see my comments below. Also, can you fix the typo in your third commit message? You didn't capitalize `add`. Please pay attention to details, especially if they were corrected originally. 

Sometimes, it's easier to copy+paste text instead of typing it out. That way, any mistakes would be on the person who originally wrote the text.

2023-06-14 23:57 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/macros/json/JSONObject.macro
> +
It looks like you're adding this twice

2023-06-14 23:57 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/paths/ObjectField.path
> +	</tr>
Out of curiosity, can we use an existing path for this dropdown menu option? We should a generic path for this

2023-06-14 23:57 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +				timeStorageOption = "useInputAsEntered");
Can we add the field using the UI here? We should have at least one test that does this

2023-06-14 23:57 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +				value = "2023-06-01T09:00:00.000Z");
Can we add the entry using the UI here? We should have at least one test that does this

2023-06-14 23:57 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +			ObjectAdmin.goToCustomObject(objectName = "CustomObject186248");
We don't need this step here

2023-06-14 23:57 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +		task ("AWhen the user views the entry") {
`When the user views the entry`

Please be careful with typos

2023-06-14 23:57 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +			ObjectAdmin.goToCustomObject(objectName = "CustomObject186247");
This should be part of the `When`, it's not part of the setup to create the object and the entry

2023-06-14 23:57 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectFieldsDateAndTime.testcase
> +		task ("When the user update the entry") {
`When the user updates the entry`

Please pay attention to the wording. This is the second typo I found.

2023-06-20 06:58 UTC, timpak approved these changes

2023-06-20 06:58 UTC, timpak commented
ci:forward

2023-06-20 06:58 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-06-20 07:05 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e5341d48364c62e329d3c551ded58f3900e3c0b5">e5341d48364c62e329d3c551ded58f3900e3c0b5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Natanaelbenvindo/liferay-portal/tree/LPS-186246">LPS-186246</a><br/>Branch GIT ID: <a href="https://github.com/Natanaelbenvindo/liferay-portal/commit/937bcbd4fcd6d625077b40d338d1d07077720266">937bcbd4fcd6d625077b40d338d1d07077720266</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/4675/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4675/jenkins-report.html">here</a>.</h5></details></html>

2023-06-20 07:05 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-38.liferay.com/job/test-portal-source-format/4675//consoleFull)

2023-06-20 07:06 UTC, closed without merging

2023-06-20 07:06 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/136597
[Console](https://test-1-38.liferay.com/job/test-portal-source-format/4675//consoleFull)

2023-06-20 07:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/4675/">test-portal-source-format#4675</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4675/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/874">liferay-bpm-qa#874</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2355479235">[master] ci:test:sf - Natanaelbenvindo &gt; liferay-bpm-qa - PR#874 - 2023-06-19[23:58:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/16846/">publish-testray-report#16846</a><br/></div></div>

2023-06-20 08:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/8016/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8016/jenkins-report.html">here</a>.</b></p>

2023-06-20 09:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/8016/">test-portal-acceptance-pullrequest(master)#8016</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8016/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/874">liferay-bpm-qa#874</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2355866089">[master] ci:test:relevant - Natanaelbenvindo &gt; liferay-bpm-qa - PR#874 - 2023-06-20[01:55:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/16849/">publish-testray-report#16849</a><br/></div></div>