LPS-186452 | Test Automation | Master
liferay-bpm-qa/liferay-portal pull request #912
Opened 2023-06-20 13:15 UTC by victorhcunha

[LPS-186468](https://liferay.atlassian.net/browse/LPS-186468)
[LPS-186467](https://liferay.atlassian.net/browse/LPS-186467)
[LPS-186452](https://liferay.atlassian.net/browse/LPS-186452)

2023-06-20 13:17 UTC, victorhcunha commented
ci:test:sf

2023-06-20 13:53 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 36 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/42246a7dccec49db7a18d3601dd299dd4b083974">42246a7dccec49db7a18d3601dd299dd4b083974</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/victorhcunha/liferay-portal/tree/LPS-186452">LPS-186452</a><br/>Branch GIT ID: <a href="https://github.com/victorhcunha/liferay-portal/commit/3d4f42650ce4ad24ce47337c9adb93089de35d1d">3d4f42650ce4ad24ce47337c9adb93089de35d1d</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1794/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1794/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
     [java] SLF4J: Defaulting to no-operation (NOP) logger implementation
     [java] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[stopwatch] [run.batch.test.action: 1:38.586 sec]
     [echo] 
      [get] Getting: http://test-1-40/job/test-portal-source-format/1794//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230620065314590.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230620065314590.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null764181589.properties</pre></details></html>

2023-06-20 13:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1794/">test-portal-source-format#1794</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1794/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/912">liferay-bpm-qa#912</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2356194250">[master] ci:test:sf - victorhcunha &gt; liferay-bpm-qa - PR#912 - 2023-06-20[06:17:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/6438/">publish-testray-report#6438</a><br/></div></div>

2023-06-21 22:48 UTC, timpak requested changes
Hey @victorhcunha please take a look at my commits below. Be careful when rebasing or fixing SF errors, you should make sure your changes are part of the right commit before forwarding it.

2023-06-21 22:48 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectPersonalData.testcase
> +	@description = "LPS-186452 - Verify that is possible to export personal data"
`Verify a user's personal data can be exported`
I didn't correct this earlier, that's my mistake. 

Also, the ticket ID should be the story ticket and not the automation ticket

2023-06-21 22:48 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectPersonalData.testcase
> +			}
Why not add the entries using the API?

2023-06-21 22:48 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectPersonalData.testcase
> +	@description = "LPS-186468 - Verify that is possible to anonymize object entries"
`Verify the object entries can be anonymized`

Same thing here, the ticket ID should be the story ticket.

2023-06-21 22:48 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectPersonalData.testcase
> +			}
Same thing here, we should add the entries using the API instead

2023-06-21 22:48 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectPersonalData.testcase
> +				userLoginFullName = "userfn userln");
Do we need to login as the 2nd user here?

2023-06-21 22:48 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectPersonalData.testcase
> +
Be careful when fixing SF errors or rebasing, this shouldn't be part of this commit. Please make sure this test is part of your third commit.

Also, don't forget to change the ticket ID to the story ticket.

2023-06-21 22:48 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectPersonalData.testcase
> +			ObjectPortlet.selectCustomObject(label = "Custom Object 186467");
Do we need to navigate back to the object admin page here? Why not go straight to the layouts tab?

2023-06-21 22:48 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectPersonalData.testcase
> +			}
Can we add the entries using the API instead?

2023-06-21 22:48 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectPersonalData.testcase
> +				userLoginFullName = "userfn userln");
Do we need to login as the 2nd user here?

2023-06-22 14:08 UTC, victorhcunha commented
ci:test:sf

2023-06-22 14:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/7348/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/7348/jenkins-report.html">here</a>.</b></p>

2023-06-22 14:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a6b4949e12df686e7c8362d96d599b5a01d934c6">a6b4949e12df686e7c8362d96d599b5a01d934c6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/victorhcunha/liferay-portal/tree/LPS-186452">LPS-186452</a><br/>Branch GIT ID: <a href="https://github.com/victorhcunha/liferay-portal/commit/de8093a7f308da9c12099d8ba0159faa660a90fe">de8093a7f308da9c12099d8ba0159faa660a90fe</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/7348/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/7348/jenkins-report.html">here</a>.</h5></details></html>

2023-06-22 15:19 UTC, victorhcunha commented
SF errors corrected, description tests updated (in the ticket too)
The next step is to refactor to do new user entries via API and remove unnecessary steps

2023-06-23 16:53 UTC, victorhcunha commented
ci:test:sf

2023-06-23 16:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/7013/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7013/jenkins-report.html">here</a>.</b></p>

2023-06-23 16:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7c849bf440923edc3fd97ff569f331a411b1aee6">7c849bf440923edc3fd97ff569f331a411b1aee6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/victorhcunha/liferay-portal/tree/LPS-186452">LPS-186452</a><br/>Branch GIT ID: <a href="https://github.com/victorhcunha/liferay-portal/commit/076f76656f1e0eb5e0ade46bfd6c1b4268661335">076f76656f1e0eb5e0ade46bfd6c1b4268661335</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7013/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7013/jenkins-report.html">here</a>.</h5></details></html>

2023-06-23 17:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7013/">test-portal-source-format#7013</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7013/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm-qa/liferay-portal/pull/912">liferay-bpm-qa#912</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2359905477">[master] ci:test:sf - victorhcunha &gt; liferay-bpm-qa - PR#912 - 2023-06-23[09:53:41]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/3361/">publish-testray-report#3361</a><br/></div></div>

2023-06-23 18:43 UTC, victorhcunha commented
Hi, @timpak !
The corrections were made.
Now all the entries are made via API, for that the logins became unnecessary and were removed. However, as the new user has no data on the portal other than the entries themselves, a new confirmation message is displayed when anonymizing and deleting the data, making the standard macros for this no longer suitable.

2023-07-11 05:58 UTC, timpak approved these changes

2023-07-11 05:59 UTC, timpak commented
ci:forward

2023-07-11 05:59 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-07-11 05:59 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2023-07-11 06:07 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-21.liferay.com/job/forward-pullrequest/409//consoleFull)

2023-07-11 06:07 UTC, closed without merging

2023-07-11 06:07 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/137653
[Console](https://test-1-21.liferay.com/job/forward-pullrequest/409//consoleFull)